// Correct texts (agent-written, 2026-10-06, round 3): nothing here may be flagged.
module.exports = {
  fr: [
    "Salut @Julien, tu as vu le message dans #général ? Le déploiement est prévu à 14h30, pas avant. 😅",
    "Bonjour à tous ! La réunion de demain est déplacée à 9h45 en salle B. Merci de confirmer votre présence avant ce soir :)",
    "Le ticket JIRA-1234 est corrigé dans la v2.3.1. Pouvez-vous tester de votre côté et me faire un retour ?",
    "J'ai payé 12,50 € pour deux cafés et un croissant. C'est un peu cher, non ?",
    "Les ventes ont augmenté de 15 % au troisième trimestre, ce qui dépasse nos prévisions.",
    "La documentation est disponible ici : https://example.com/docs?lang=fr&page=2. N'hésitez pas à la partager.",
    "Liste de courses :\n- acheter du pain\n- appeler maman\n- passer à la pharmacie\n- récupérer le colis",
    "« Tu viens ce soir ? » demanda-t-elle. « Bah, je ne sais pas encore », répondit-il en haussant les épaules.",
    "Ouais, c'est bon, j'ai compris. Euh, tu peux juste m'envoyer le lien encore une fois ?",
    "Hmm, je crois qu'il y a un souci avec le build de cette nuit. Quelqu'un peut jeter un œil ?",
    "Pour redémarrer le service, lancez `sudo systemctl restart nginx` puis vérifiez le fichier /etc/nginx/nginx.conf.",
    "Le fichier de configuration se trouve dans C:\\Users\\me\\AppData\\Roaming\\app. Ne le supprimez surtout pas.",
    "On a eu un call avec le client ce matin, et le feedback est plutôt positif dans l'ensemble.",
    "Le « dashboard » affiche maintenant les indicateurs en temps réel. Il reste quelques ajustements à faire sur les graphiques.",
    "Il fallut attendre l'aube pour que la tempête s'apaisât enfin. Les pêcheurs regagnèrent alors le port en silence.",
    "Quoiqu'il fût tard, elle voulut qu'on lui lût encore une page.",
    "Peut-être viendra-t-il demain ; peut-être ne viendra-t-il jamais. Nul ne saurait le dire.",
    "M. Dupont et Mme Lefèvre ont été reçus par le Dr Martin à 10 heures précises.",
    "Veuillez indiquer votre n° de dossier, p. ex. 2025-00417, dans l'objet de votre courriel.",
    "Le prix comprend l'hébergement, c.-à-d. la chambre et le petit-déjeuner, mais pas les repas du soir.",
    "La cérémonie aura lieu le 1er janvier 2025 au 12, rue des Lilas, 75011 Paris.",
    "Vous pouvez nous joindre au 01 23 45 67 89 du lundi au vendredi, de 9 h à 18 h.",
    "Le PSG s'est imposé 3 à 1 face à l'OM dimanche soir, au terme d'un match très disputé.",
    "Pour la pâte, mélangez 250 g de farine, 3 œufs et 50 cl de lait. Laissez reposer une heure au frais.",
    "La molécule d'eau, H2O, est composée de deux atomes d'hydrogène et d'un atome d'oxygène.",
    "Les émissions de CO2 du secteur ont baissé de 4,2 % par rapport à l'an dernier.",
    "La vitesse de la lumière est d'environ 3 × 10⁸ m/s dans le vide.",
    "Nguyễn Văn An a ouvert un restaurant à Lyon, où il sert des phở que tout le quartier adore.",
    "Siobhán est arrivée de Dublin hier soir ; elle repart pour Zürich jeudi matin.",
    "Nous avons passé une semaine à Oaxaca, puis quelques jours à Mexico avant de rentrer.",
    "J'ai acheté une glace Häagen-Dazs et un iPhone d'occasion sur eBay. Drôle de journée !",
    "Elle regarde des tutoriels sur YouTube pendant que son frère mange chez McDonald's.",
    "Wow, bravo pour la mise en production ! 🎉 Franchement, l'équipe a fait un super travail.",
    "Oups, j'ai envoyé le mauvais fichier. Voici la bonne version, désolé pour le dérangement.",
    "#annonce Le serveur sera en maintenance samedi de 22h à 2h. Merci de votre compréhension 🙏",
    "Requête à exécuter : `SELECT nom, prenom FROM clients WHERE ville = 'Lyon';` Elle renvoie environ 200 lignes.",
    "L'erreur « 404 Not Found » apparaît quand on clique sur le lien du menu. Je pense que la route n'est pas déclarée.",
    "Dans le JSON, la clé `user_id` doit être un entier, et la clé `email` une chaîne de caractères.",
    "N'oubliez pas : les champs en **gras** sont obligatoires, et les commandes s'écrivent entre accents graves, comme `ls -la`.",
    "Le chat de la voisine fit « miaou » trois fois, puis s'endormit sur le rebord de la fenêtre.",
    "Toc, toc ! Qui est là ? Personne ne répondit, et la porte resta close.",
    "Si j'avais su, je serais venu plus tôt. Mais personne ne m'avait prévenu.",
    "Il faut que tu viennes avant midi, sinon nous partirons sans toi.",
    "Bien qu'elle soit fatiguée, elle a tenu à terminer son rapport avant de partir.",
    "Les enfants se sont lavé les mains avant de passer à table.",
    "Les fleurs que j'ai cueillies ce matin sont déjà fanées.",
    "Ils se sont souvenus de leurs vacances en Bretagne avec beaucoup de nostalgie.",
    "Quelle que soit ta décision, je la respecterai.",
    "Quels que soient les obstacles, nous tiendrons nos engagements.",
    "Tout le monde est arrivé à l'heure, sauf Paul, qui s'était trompé de gare.",
    "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.",
    "Conformément à l'article 5 du contrat, le preneur s'engage à restituer les lieux en bon état.",
    "Le présent avenant prend effet à compter de sa signature par les deux parties.",
    "Dans cet article, nous montrons que les résultats obtenus confirment l'hypothèse initiale, à savoir une corrélation entre les deux variables.",
    "Vingt-trois personnes ont répondu au sondage, dont dix-sept se disent satisfaites.",
    "Il a couru les dix kilomètres en quarante-deux minutes, un record personnel.",
    "Le train de 7h12 a été supprimé ; prenez celui de 7h42, voie 3.",
    "FYI, la démo est reportée à jeudi. Je vous envoie l'invitation ASAP.",
    "PS : n'oubliez pas d'apporter vos badges, l'accès au bâtiment sera contrôlé.",
    "@Camille, je t'ai assignée sur le ticket. Tu peux regarder quand tu as un moment ? Merci !",
    "Le nouveau MacBook coûte 1 499 € en France, contre 1 299 $ aux États-Unis.",
    "Le taux de conversion est passé de 2,1 % à 3,4 % après la refonte de la page d'accueil.",
    "Mise à jour vers la version 4.0.2 terminée. Redémarrez l'application pour appliquer les changements.",
    "Je rentre de Kyoto, où j'ai visité le temple Kinkaku-ji. C'était magnifique sous la neige.",
    "Björk, Ólafur Arnalds et Sigur Rós sont des artistes islandais très connus.",
    "Nous dînerons chez Giuseppe, une petite trattoria près de la gare de Bologne.",
    "Après le stand-up, on fait un point rapide sur la roadmap du prochain trimestre.",
    "Le commit est en attente de relecture depuis lundi. Quelqu'un pourrait-il s'en charger ?",
    "Ah bon ? Je pensais que tu étais déjà parti. Tant mieux, on va pouvoir déjeuner ensemble !",
    "Chut ! Le bébé dort enfin. Parle moins fort, s'il te plaît.",
    "Hélas ! Le navire sombra avant que l'équipage pût atteindre la côte.",
    "Ainsi parla le vieil homme, et nul n'osa lui répondre.",
    "À peine fut-il sorti qu'il se mit à pleuvoir.",
    "Puissiez-vous trouver le bonheur que vous méritez !",
    "Rendez-vous à 18 h devant le cinéma, on prendra un verre après la séance. 🍿",
    "Quelqu'un a-t-il le mot de passe du Wi-Fi de la salle de réunion ?",
    "Les températures descendront jusqu'à -5 °C cette nuit dans le Jura.",
    "Le colis n° 4587 a été expédié le 3 mars et devrait arriver sous 48 heures.",
    "Préchauffez le four à 180 °C. Faites cuire le gâteau pendant 35 minutes, puis laissez-le refroidir.",
    "La solution contient 0,5 mol/L de NaCl, soit environ 29 g de sel par litre.",
    "Les élèves ont lu trois romans de Zola cette année, dont Germinal et L'Assommoir.",
    "Merci pour ton aide d'hier ! Sans toi, je n'aurais jamais fini à temps 😊",
    "Est-ce que tu peux relancer le job ? Le test d'intégration a échoué à cause d'un timeout.",
    "Le site affiche « Erreur 500 : Internal Server Error » depuis ce matin. On est dessus, je vous tiens au courant.",
    "Pour installer les dépendances, tapez `npm install` dans le terminal, puis `npm run dev`.",
    "Elle a obtenu 18 sur 20 à l'examen, la meilleure note de la classe.",
    "Le marathon de Berlin aura lieu dimanche ; plus de 40 000 coureurs sont attendus.",
    "Je me permets de vous relancer, car je n'ai pas encore reçu votre réponse concernant le devis du 12 février.",
    "Les résultats seront publiés sur https://www.example.org/resultats avant la fin du mois.",
    "Vous trouverez ci-joint le compte rendu de la réunion ainsi que la liste des actions à mener.",
  ],
  en: [
    "Hey @sam, did you see the update in #general? The deploy is scheduled for 9:45am, not 9:15. 😅",
    "FYI, the fix for JIRA-1234 shipped in v2.3.1. Let me know if you still see the bug.",
    "The new laptop costs $1,299.99, which is about 20% more than last year's model.",
    "Docs are here: https://example.com/path?x=1. Ping me if anything is unclear :)",
    "Shopping list:\n- buy bread\n- call Mom\n- pick up the dry cleaning\n- book the dentist",
    "“Are you coming tonight?” she asked. “Hmm, I'm not sure yet,” he replied.",
    "Wow, that was fast! Thanks for jumping on the call on such short notice.",
    "Oops, I sent the wrong file. Here's the correct version; sorry about that.",
    "To restart the server, run `sudo systemctl restart nginx` and then check /etc/nginx/nginx.conf for errors.",
    "The logs are stored in C:\\Users\\me\\AppData\\Local\\Temp by default.",
    "The query `SELECT id, name FROM users WHERE active = 1;` returns about 3,000 rows.",
    "The API returns a JSON object with the keys `status`, `data`, and `error`.",
    "I got a “TypeError: Cannot read properties of undefined” error when I clicked the button.",
    "Make sure the **required** fields are filled in before you submit the form.",
    "We had crème brûlée and two cups of café au lait after dinner.",
    "I had a strong sense of déjà vu when I walked into the room.",
    "Customer satisfaction is the company's raison d'être, according to its founder.",
    "Nguyễn Thị Mai moved from Hanoi to Toronto in 2019 and now runs a small bakery.",
    "Siobhán and her cousin flew from Dublin to Zürich for the conference.",
    "We spent a week in Oaxaca eating mole and visiting the markets.",
    "She bought a pint of Häagen-Dazs, then ordered a new iPhone case on eBay.",
    "My nephew watches YouTube videos while eating fries from McDonald's.",
    "The meeting is on March 3rd at 2:30 p.m. in Conference Room B.",
    "Please send your RSVP ASAP, i.e., by Friday at the latest.",
    "Bring something to share, e.g., chips, salsa, or a dessert.",
    "Dr. Patel and Mr. Okafor will present the findings at the board meeting.",
    "PS: Don't forget to bring your badge, since security will check IDs at the entrance.",
    "Our office is at 221 Baker Street, London NW1 6XE. You can call us at +44 20 7946 0958.",
    "The Lakers beat the Celtics 112–108 in overtime last night.",
    "Whisk together 2 cups of flour, 1 teaspoon of baking soda, and a pinch of salt.",
    "Preheat the oven to 350°F and bake for 25 to 30 minutes, or until golden brown.",
    "Water (H2O) and carbon dioxide (CO2) are both products of combustion.",
    "Avogadro's number is approximately 6.022 × 10²³ per mole.",
    "Had I known about the delay, I would have taken an earlier train.",
    "If I were you, I would apply for the position before the deadline.",
    "The committee recommends that each member submit a written report by June 30.",
    "Notwithstanding the foregoing, the Licensee shall not sublicense any rights granted herein.",
    "This Agreement shall be governed by and construed in accordance with the laws of the State of New York.",
    "Previous studies have suggested that sleep deprivation impairs memory consolidation; however, the underlying mechanisms remain unclear.",
    "The data were collected over a period of six months and analyzed using a mixed-effects model.",
    "Thirty-two participants completed the survey, and nineteen of them reported improved focus.",
    "Ugh, the build failed again. Can someone take a look at the CI logs? 🙏",
    "Heads up: #random is getting archived next week, so please move anything important to #team-updates.",
    "Our conversion rate went from 2.1% to 3.4% after the redesign.",
    "Version 4.0.2 is out! Restart the app to apply the update.",
    "Thanks for the help yesterday! I couldn't have finished on time without you 😊",
    "Lunch is at 12:30 at the usual place. Who's in?",
    "Shh! The baby is finally asleep.",
    "Knock, knock. Who's there? Nobody answered, so I left the package by the door.",
    "The dog barked—woof, woof!—and the mail carrier hurried back to the van.",
    "Björk, Sigur Rós, and Ólafur Arnalds are all from Iceland.",
    "We had dinner at a small trattoria near the train station in Bologna.",
    "Neither the manager nor the employees were aware of the change.",
    "Each of the students has submitted a final project.",
    "The number of applicants has increased steadily since 2020.",
    "Whom should I contact regarding the invoice dated February 12?",
    "It's important to check its settings before you run the script.",
    "There are fewer errors in this release than in the previous one.",
    "Their house is over there, and they're planning to sell it next spring.",
    "Your order #4587 shipped on May 5 and should arrive within 48 hours.",
    "Run `npm install` and then `npm run dev` to start the local server on port 3000.",
    "The temperature dropped to -5°C overnight, so the roads were icy this morning.",
    "She ran the marathon in 3 hours and 42 minutes, a personal best.",
    "Please find attached the minutes of the meeting and the list of action items.",
    "I am writing to follow up on my application for the Senior Analyst position, which I submitted on September 14.",
    "Kind regards,\nEmily Zhang\nProject Manager",
    "We need to finalize the roadmap by Q4; otherwise, the launch will slip.",
    "The patient was prescribed 500 mg of amoxicillin three times a day for seven days.",
    "Visit https://www.example.org/signup?ref=newsletter to create your free account.",
    "Haha, that meme in #off-topic made my day 😂",
    "The ballet was performed at the Bolshoi Theatre in Moscow, and the critics were enthusiastic.",
    "José and María opened a café in São Paulo that serves excellent coffee.",
    "Hmm, I don't think that's right. Could you double-check the numbers in row 12?",
    "The ratio of hydrogen to oxygen in water is 2:1.",
    "Our team won 3–1, and Sarah scored two of the goals.",
    "Seldom have I seen such a well-organized event.",
    "Not only did she finish the report, but she also prepared the slides.",
    "The error message says “Permission denied (publickey).” Did you add your SSH key to GitHub?",
    "Mrs. O'Brien teaches French at the local high school; her students adore her.",
    "Call me at (555) 123-4567 after 6 p.m., or email me if that's easier.",
  ],
};
for (const lang of ["fr", "en"]) module.exports[lang] = module.exports[lang].map((s) => [s, null, null]);
