// Correct everyday texts (agent-written, 2026-10-06): nothing here may be flagged.
// French texts first (fr), English texts (en).
module.exports = {
  fr: [
    "Salut Julie, tu es dispo samedi pour un ciné ?",
    "Coucou ! On se retrouve à 14 h 30 devant la gare, ça te va ?",
    "Bonjour Madame Lefèvre, je vous remercie pour votre réponse rapide. Je vous envoie les documents demandés dès demain matin. Bien à vous, Claire Martin",
    "Bonsoir à tous, la réunion de jeudi est reportée au 12/05/2026 à 10 h. Merci de confirmer votre présence par retour de mail.",
    "T'inquiète, je m'en occupe ce soir.",
    "C'est trop bien, merci pour le cadeau ! Bisous",
    "Ouais, je sais pas trop, on verra demain.",
    "Il a fini son travail et il est parti à la plage.",
    "Où est-ce que tu as mis les clés ? Je ne les trouve plus.",
    "Tu préfères du thé ou du café ?",
    "Les fleurs que tu m'as offertes sont magnifiques.",
    "La lettre que j'ai écrite hier est déjà partie.",
    "Je suis las de ces réunions qui ne servent à rien.",
    "Il est né à Lyon en 1987 et vit à Marseille depuis dix ans.",
    "Nous partons dans trois mois pour le Japon, j'ai hâte !",
    "Dans son for intérieur, il savait qu'elle avait raison.",
    "Le mont Blanc culmine à plus de 4 800 mètres.",
    "Achète du pain, du lait et deux baguettes en rentrant, s'il te plaît.",
    "Il faut que tu viennes avant midi, sinon on partira sans toi.",
    "Si j'avais su, je serais venu plus tôt.",
    "Si tu veux, on peut plutôt manger chez moi.",
    "Quel dommage qu'elle ne puisse pas venir ce week-end !",
    "Je pense qu'elle arrivera vers 19 h, mais je ne suis pas sûr.",
    "Il est peu probable qu'il pleuve demain, mais on ne peut jamais savoir.",
    "Il peut venir avec nous s'il le souhaite.",
    "Tous les invités sont arrivés et tout le monde a apporté quelque chose à manger.",
    "Ces chaussures sont à moi, mais ses lunettes sont restées sur la table.",
    "Ses parents sont venus le chercher à la sortie de l'école.",
    "Je leur ai dit de prendre leurs affaires avant de partir.",
    "Elle se demande ce qu'il va faire après son bac.",
    "Le chat est là, sous le canapé. Je l'ai vu tout à l'heure.",
    "Il s'en est allé sans dire au revoir.",
    "Je ne m'en souviens plus, mais je vais vérifier dans mes notes.",
    "Recette du jour : faites fondre 100 g de beurre, ajoutez 2 œufs et 150 g de sucre, puis mélangez bien.",
    "Préchauffez le four à 180 °C et enfournez pendant 25 minutes.",
    "Super produit, livré en deux jours. La batterie tient facilement une journée entière. Je recommande !",
    "Déçue par cet achat : la couleur ne correspond pas du tout à la photo et la taille est trop petite.",
    "Très bon restaurant, le service était rapide et les plats copieux. Comptez environ 25 € par personne.",
    "Mdr, j'ai cru que tu parlais sérieusement !",
    "On y va ? Le film commence dans dix minutes.",
    "Tu peux m'envoyer le lien ? Mon adresse, c'est julie.dupont@gmail.com.",
    "Toutes les infos sont sur notre site : https://www.exemple.fr/inscription.",
    "Merci à @marie_l pour cette belle soirée ! #anniversaire #amis",
    "Bonjour M. Benali, je me permets de vous relancer au sujet de la facture n° 2045. Cordialement, Sophie Girard",
    "Mme Nguyễn sera absente jusqu'au 15 octobre. Pour toute question urgente, contactez le secrétariat.",
    "Le Dr Kowalski reçoit uniquement sur rendez-vous, du lundi au vendredi.",
    "Łukasz et Zoë nous ont invités à leur mariage en juin prochain.",
    "José m'a prêté son vélo pour la journée, c'est vraiment sympa de sa part.",
    "Fatima et Youssef ont ouvert une boulangerie rue de la République.",
    "Prévoir pour la sortie : un pique-nique, une gourde, une casquette et de la crème solaire.",
    "Il fait beau aujourd'hui, on pourrait aller se promener au parc.",
    "Les résultats seront publiés le 3 juillet sur l'espace numérique de travail.",
    "À la suite de la tempête, plusieurs routes ont été fermées dans le Finistère.",
    "Le gouvernement a annoncé une hausse de 2 % du budget consacré à l'éducation.",
    "La mairie organise une collecte de vêtements samedi de 9 h à 12 h.",
    "Note : rappeler le fournisseur avant vendredi et mettre à jour le tableau de suivi.",
    "Points à aborder lors de la réunion : le budget, le planning et le recrutement.",
    "Exercice 3 : conjuguez les verbes entre parenthèses au passé composé.",
    "Victor Hugo a publié Les Misérables en 1862.",
    "La Seine traverse Paris d'est en ouest.",
    "Les élèves que j'ai rencontrés étaient très motivés.",
    "Elle s'est lavé les mains avant de passer à table.",
    "Elle s'est levée tôt ce matin pour aller courir.",
    "Les pommes que j'ai achetées sont déjà mûres.",
    "Combien de livres as-tu lus cet été ?",
    "Je doute qu'il soit prêt à temps pour la présentation.",
    "Bien qu'il fasse froid, nous sommes sortis faire un tour.",
    "Pourvu qu'il fasse beau dimanche !",
    "J'aimerais que vous me rappeliez dès que possible.",
    "Si tu avais le temps, tu pourrais m'aider à déménager ?",
    "Si elle vient, je lui présenterai mes cousins.",
    "Ça fait plaisir de te voir ! Ça faisait longtemps.",
    "Bon courage pour ton examen demain, tu vas tout déchirer 💪",
    "Joyeux anniversaire ma belle ! 🎉 Passe une super journée.",
    "Je t'appelle quand je sors du boulot, vers 18 h.",
    "C'est pas grave, ça arrive à tout le monde.",
    "J'ai pas eu le temps de finir, désolée.",
    "Je trouve pas mes clés, tu les as vues ?",
    "Je veux pas te déranger, mais tu aurais deux minutes ?",
    "On sait jamais, prends un parapluie.",
    "Il y a personne au bureau aujourd'hui, c'est calme.",
    "Ça me dit rien, mais je veux bien essayer.",
    "Je comprends pas pourquoi il a dit ça.",
    "T'en fais pas, ça va bien se passer.",
    "Il vient pas ce soir, il est malade.",
    "Je sais pas si je pourrai venir, je te redis.",
    "Laisse tomber, c'est pas important.",
    "Je savais pas que tu étais rentrée de vacances !",
    "Je peux pas ce soir, on remet ça à demain ?",
    "Tu vas pas le croire, j'ai gagné au loto !",
    "Tu viens ou pas ? On t'attend en bas.",
    "La réunion a été annulée parce que la directrice était souffrante.",
    "Le colis a été livré à 11 h 45 et déposé chez le gardien.",
    "Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.",
    "Madame, Monsieur, je souhaite postuler au poste d'assistant administratif publié sur votre site. Vous trouverez ci-joint mon CV et ma lettre de motivation.",
    "Bonne journée à toi aussi, et encore merci pour ton aide !",
    "Pense à prendre ta carte Vitale pour le rendez-vous chez le médecin.",
    "Le train pour Bordeaux partira de la voie B avec un retard d'environ 20 minutes.",
    "Nous avons pris le TGV jusqu'à Nice, puis un bus jusqu'à Menton.",
    "J'ai commandé une pizza quatre fromages et une salade César.",
    "Quelle heure est-il ? Je crois que ma montre s'est arrêtée.",
    "Quelle belle surprise ! Je ne m'y attendais pas du tout.",
    "Je ne sais pas quel film choisir, tu as une idée ?",
    "Elle est plus grande qu'elle ne le paraît sur les photos.",
    "Ces deux maisons sont à vendre depuis l'année dernière.",
    "Deux cafés et un croissant, s'il vous plaît.",
    "Il y a deux ans, nous habitions encore à Strasbourg.",
    "C'est la plus belle ville que j'aie jamais visitée.",
    "Où que tu ailles, n'oublie pas de m'écrire.",
    "Tu peux venir lundi ou mardi, comme tu préfères.",
    "Le chien a mangé sa gamelle et s'est endormi au soleil.",
    "Elle a rangé sa chambre et elle est allée faire les courses.",
    "Ils ont décidé de vendre leur voiture pour acheter des vélos.",
    "Il est déjà 20 h, et le dîner n'est toujours pas prêt.",
    "Est-ce que tu as pensé à arroser les plantes ?",
    "Les enfants sont partis en colonie de vacances pour deux semaines.",
    "Mon frère, qui habite à Montréal, vient nous voir à Noël.",
    "Grâce à toi, j'ai enfin compris les fractions !",
    "Tout le monde est d'accord : on part à 8 h précises.",
    "Ils sont tous venus, même ceux qui habitent loin.",
    "Elles étaient toutes ravies de se revoir après tant d'années.",
    "Il a tout mangé, il ne reste plus rien.",
    "Merci beaucoup pour votre accueil chaleureux, nous avons passé un excellent séjour. À bientôt, Ahmed et Leïla",
    "Mon téléphone ne s'allume plus depuis ce matin, je pense que la batterie est morte.",
    "Le magasin est fermé le dimanche et les jours fériés.",
    "Le musée du Louvre accueille près de neuf millions de visiteurs par an.",
    "La Bretagne est connue pour ses crêpes, ses phares et ses côtes sauvages.",
    "N'hésitez pas à me contacter au 06 12 34 56 78 si besoin.",
    "Le prix est passé de 49,90 € à 39,90 € pendant les soldes.",
    "Je suis vraiment contente que tu sois venue.",
    "C'est la première fois que je vois un spectacle aussi drôle.",
    "Lisez le texte p. 45 et répondez aux questions 1 à 4.",
    "On peut utiliser des légumes de saison, p. ex. des courgettes, des tomates ou des aubergines.",
    "J'ai acheté des fruits, des légumes, du fromage, etc.",
    "Aïcha a obtenu son permis du premier coup, bravo à elle !",
    "Ça y est, on a enfin trouvé un appartement !",
    "Je me suis trompé de bus, j'arriverai avec un peu de retard.",
    "Nous nous sommes promenés le long du canal Saint-Martin.",
    "Elle s'est rendu compte de son erreur trop tard.",
    "Les vacances se sont bien passées, merci de nous avoir prêté la maison.",
    "Est-ce qu'il a déjà déjeuné ou est-ce qu'il attend ?",
    "La voiture qu'il a achetée est rouge.",
    "Les gâteaux qu'elle a faits étaient délicieux.",
    "Il faut absolument que nous parlions de ce projet avant lundi.",
    "Je voudrais réserver une table pour quatre personnes samedi soir, à 20 h 30.",
    "Le rapport est presque terminé ; il me reste la conclusion à rédiger.",
    "Elle lit beaucoup : des romans, des essais et des bandes dessinées.",
    "« Le temps, c'est de l'argent », répétait souvent mon grand-père.",
    "Comme le disait Saint-Exupéry : « On ne voit bien qu'avec le cœur. »",
    "Qu'est-ce que tu fais ce soir ? Si tu veux, on peut se faire un resto.",
    "Désolé pour le retard, il y avait des bouchons sur le périphérique.",
    "Bises à toute la famille, et à très vite !",
    "Le cours de yoga a lieu chaque mardi de 18 h 30 à 19 h 30 à la salle polyvalente.",
    "Le patient doit prendre un comprimé matin et soir pendant sept jours.",
    "Notre équipe a gagné trois à un, quel match !",
    "Ce n'est pas ce que je voulais dire, mais je comprends ta réaction.",
    "Elle a ses habitudes : un café le matin, une promenade l'après-midi.",
    "Il se peut qu'il neige cette nuit sur les hauteurs.",
    "Mon fils a eu 17 sur 20 en maths, il était fier de lui.",
    "Ce sont mes amis qui ont organisé la fête.",
    "Son ordinateur et ses écouteurs sont sur le bureau.",
    "Il l'a appelée trois fois, mais elle n'a pas répondu.",
    "Je l'ai rencontrée à Lisbonne pendant mes études.",
    "Plus tôt tu partiras, moins il y aura de bouchons.",
    "Il est arrivé plus tôt que prévu, alors on a pris un verre en terrasse.",
    "Les fichiers sont dans le dossier partagé, je les ai renommés pour plus de clarté.",
    "Pour rappel, le télétravail est possible deux jours par semaine.",
    "Ana María et Jiří viennent dîner à la maison vendredi.",
    "Kenji m’a appris à préparer des ramens maison, c’était délicieux.",
    "Svetlana a terminé son marathon en 3 h 52, quelle performance !",
  ],
  en: [
    "Hi Tom, are you free on Saturday for a movie?",
    "Hey! Wanna grab lunch tomorrow? I'm thinking about that new Thai place on Main Street.",
    "Dear Ms. Patel, thank you for your quick reply. I'll send the signed contract by Friday. Best regards, John",
    "Hi everyone, just a reminder that the team meeting has been moved to 3:30 pm on Thursday.",
    "Their house is just over there, and they're having a barbecue tonight.",
    "It's been a long week, and the company has finally announced its new policy.",
    "She's taller than her brother, but he's older.",
    "We had dinner, and then we went for a walk along the river.",
    "The new rules didn't affect our schedule much, but they had a big effect on the budget.",
    "Whose jacket is this? Who's coming to pick it up?",
    "Be careful not to lose your keys. The ring is a bit loose.",
    "Thanks for the invite! I'd love to.",
    "You don't have to come if you don't want to.",
    "I'm not sure whether the weather will be good enough for a picnic.",
    "Lol, I totally forgot about that. Thanks for reminding me!",
    "Btw, I'm gonna be about ten minutes late. Traffic is terrible.",
    "Yeah, it was kinda boring, but the ending was great.",
    "Great product! It arrived in two days and works exactly as described. Five stars.",
    "Disappointed with this blender. The lid cracked after a week, and customer service never replied.",
    "The pasta was delicious, and the staff were super friendly. Expect to pay around $40 for two.",
    "Recipe: mix 2 cups of flour, 1 teaspoon of baking soda and a pinch of salt, then add the butter.",
    "Bake at 350°F for 25 minutes, or until golden brown.",
    "Shopping list: eggs, milk, bread, apples and coffee.",
    "Please send the final report to anna.smith@example.com by 12/05/2026.",
    "Check out our new website at https://www.example.com and let us know what you think!",
    "Huge thanks to @sarah_codes for the amazing talk today! #DevConf #TechTalk",
    "Dr. Nguyễn will see you at 10:15 am. Please arrive a few minutes early.",
    "Mr. and Mrs. García are celebrating their 30th anniversary this weekend.",
    "Zoë and Łukasz moved to Berlin last spring.",
    "José made the best paella I've ever had.",
    "Aisha just got promoted to senior engineer. So proud of her!",
    "Happy birthday, Mom! 🎂 Love you so much.",
    "Congrats on the new job! 🎉 You totally deserve it.",
    "If I had more time, I would learn to play the piano.",
    "If it rains tomorrow, we'll stay inside and play board games.",
    "If I were you, I'd call the landlord right away.",
    "The city council approved a new bike lane on Oak Avenue on Tuesday.",
    "Heavy snow is expected across the region this weekend, according to forecasters.",
    "Local bakery wins national award for its sourdough bread.",
    "Notes from today's call: finalize the budget, update the roadmap and schedule interviews.",
    "Before the trip, I need to renew my passport, book the hotel and buy travel insurance.",
    "Bring something warm to wear, e.g., a fleece or a light jacket.",
    "The test covers chapters 3 to 5, i.e., everything we studied in October.",
    "We need office supplies: pens, paper, staples, etc.",
    "Homework: write five sentences using the past perfect tense.",
    "The Amazon River flows through Peru, Colombia and Brazil.",
    "Shakespeare wrote Hamlet around 1600.",
    "Water boils at 100 degrees Celsius at sea level.",
    "\"Never give up,\" my coach always said.",
    "As the old saying goes, \"The early bird catches the worm.\"",
    "There are three reasons why I can't come: work, the kids and the weather.",
    "They're going to the beach, but their car is in the shop, so they'll take the bus.",
    "It's obvious that the dog wants its dinner.",
    "I'd rather walk than take the bus.",
    "First, preheat the oven. Then, grease the pan.",
    "Who's ready for the weekend? 🙌",
    "Can you tell me whose turn it is to do the dishes?",
    "These jeans are too loose, so I'm gonna return them.",
    "Don't worry, you won't lose anything if you cancel before Friday.",
    "Thanks so much for your help today. I really appreciate it.",
    "Sorry, I can't make it tonight. Maybe next time?",
    "See you at 7! Don't forget the snacks.",
    "Hope you're feeling better. Let me know if you need anything.",
    "Just landed in Tokyo! The flight was long, but totally worth it.",
    "Our team won 3-1 last night. What a game!",
    "The meeting ran late, so I missed my train.",
    "Could you please review the attached document and let me know if you have any questions? Kind regards, Emily Chen",
    "Hi Mark, I hope you're doing well. I'm following up on my email from last week regarding the invoice. Best, Sarah",
    "Thank you for your order! Your package will arrive within 3 to 5 business days.",
    "The store is closed on Sundays and public holidays.",
    "Where are you? We've been waiting for twenty minutes.",
    "What time does the concert start?",
    "How was your trip to Barcelona?",
    "I can't believe it's already October!",
    "Wow, that's amazing news!",
    "The kids have been playing outside all afternoon.",
    "She has lived in London since 2015.",
    "I've never seen such a beautiful sunset.",
    "By the time we arrived, the movie had already started.",
    "He said he would call me back, but he never did.",
    "We're out of milk. Could you pick some up on your way home?",
    "Yeah, I know, I'm kinda nervous about the interview.",
    "Gonna be a busy day, but I'll text you later.",
    "Wanna come over and watch the game?",
    "Lol, that cat video made my day.",
    "I'm not sure, to be honest. What do you think?",
    "Your package has been delivered to the front desk.",
    "The price dropped from $59.99 to $39.99 during the sale.",
    "The temperature will drop to 5°C tonight, so bring a coat.",
    "Ms. Kowalski teaches history at our school.",
    "Mohammed and Fatima are hosting a dinner party on Friday.",
    "Priya, Diego and Mei are on the organizing committee this year.",
    "Can you call me back at 555-0134 when you get a chance?",
    "Every student needs to bring a laptop and a charger.",
    "Neither of the answers is correct.",
    "The results show a clear upward trend.",
    "Less sugar and fewer calories make this recipe a healthier option.",
    "Let's meet at the café on Rue de Rivoli at noon.",
    "The Eiffel Tower is about 330 meters tall.",
    "Mount Everest is the highest mountain in the world.",
    "I'm reading a great book about the history of New York.",
    "Thanks for the feedback! We've fixed the bug in version 2.3.",
    "The server will be down for maintenance from 1:00 to 3:00 am on Sunday.",
    "Please don't hesitate to reach out if you have any questions.",
    "Looking forward to hearing from you. Best regards, Olivia Brown",
    "I wish I had studied harder for the exam.",
    "It's time we left; it's getting dark.",
    "She asked whether I wanted tea or coffee.",
    "Whether you like it or not, we're leaving at 8.",
    "The weather was perfect for a hike, so we went up the hill.",
    "The medicine took effect within an hour.",
    "That's the guy whose car got towed yesterday.",
    "Who's bringing dessert to the potluck?",
    "Their dog is friendlier than ours.",
    "I'm going there tomorrow, and then I'll head home.",
    "That's more expensive than I thought.",
    "Do you want to come? You don't have to, but it would be fun.",
    "I haven't decided yet, but I'm planning to.",
    "Ask Jake if he wants to.",
    "Just finished my first 10K run! 🏃 Feeling great.",
    "Pro tip: add a little lemon juice to keep the avocado from turning brown.",
    "Our new store opens on May 12 at 9 am. See you there!",
    "Can't wait for the holidays! Only two weeks to go.",
    "Mrs. Thompson's class raised $1,200 for the local animal shelter.",
    "How's the new apartment? I bet the view is incredible.",
    "Don’t forget to water the plants while I’m away, okay?",
  ],
};

// Same format as the other corpora: [sentence, null, null].
for (const lang of ["fr", "en"]) module.exports[lang] = module.exports[lang].map((s) => [s, null, null]);
