// Correct texts (agent-written, 2026-10-06, round 4): nothing here may be flagged.
module.exports = {
  fr: [
    "Très bon restaurant, service rapide et souriant. Les pâtes étaient parfaitement cuites. Note : 4,5/5.",
    "Livraison en deux jours, colis bien emballé. Le casque est confortable, mais l’autonomie annoncée me semble un peu optimiste. Ma note : 4/5.",
    "Déçue par cet aspirateur : il fait beaucoup de bruit et le réservoir se remplit trop vite. Je ne le recommande pas. Note : 2/5.",
    "Entreprise de logistique basée à Lyon recherche un assistant administratif ou une assistante administrative en CDI. Vous maîtrisez les outils bureautiques et avez le sens de l’organisation. Salaire : 2 100 € brut mensuel.",
    "Poste : développeur web confirmé (H/F). Lieu : Nantes, télétravail possible deux jours par semaine. Compétences attendues : JavaScript, PHP et bases de données SQL. Rémunération selon profil.",
    "À vendre : appartement T3 de 68 m² au troisième étage avec ascenseur. Séjour lumineux, cuisine équipée, deux chambres et balcon exposé sud. Prix : 245 000 €, frais d’agence inclus.",
    "À louer à Bordeaux, maison de 110 m² avec jardin clos de 400 m². Trois chambres, une salle de bains et un garage. Loyer : 1 350 € charges comprises. Disponible à partir du 1er novembre.",
    "Studio meublé de 22 m² proche de la gare, idéal pour un étudiant. Chauffage individuel électrique, DPE classe D. Visites le samedi matin uniquement.",
    "Vends vélo de ville en bon état, taille M, avec panier et antivol. Prix : 120 €, à débattre. Contactez-moi par message.",
    "Je donne deux chatons de deux mois, sevrés et propres, contre bons soins. Ils sont vaccinés et habitués aux enfants.",
    "Perdu samedi soir dans le quartier Saint-Michel : chat noir avec un collier rouge. Il répond au nom de Filou. Merci de m’appeler si vous l’apercevez.",
    "Le Stade toulousain s’est imposé 27 à 19 face à Clermont, samedi après-midi. Grâce à cette victoire, les Toulousains prennent la tête du classement.",
    "Football, Ligue 1 : Lens et Marseille se sont quittés sur un match nul (1-1). Les deux buts ont été marqués en seconde période.",
    "Tennis : la Française s’est inclinée en trois sets (6-4, 3-6, 7-5) au deuxième tour. Elle a néanmoins réalisé un très bon début de saison.",
    "Marathon de Paris : le vainqueur a franchi la ligne en 2 h 06 min 31 s, un record de l’épreuve. Plus de 50 000 coureurs avaient pris le départ.",
    "Demain, le temps sera nuageux sur la moitié nord du pays avec quelques averses en fin de journée. Les températures maximales varieront entre 14 et 18 °C.",
    "Vigilance orange aux orages dans le Sud-Est jusqu’à jeudi matin. Des rafales de vent atteignant 100 km/h sont attendues sur le littoral.",
    "Ce week-end, le soleil s’imposera partout, sauf en Bretagne où quelques nuages persisteront. Il fera jusqu’à 25 °C à Marseille.",
    "Élève sérieuse et appliquée. Les résultats sont satisfaisants, mais Léa doit participer davantage à l’oral. Bon trimestre dans l’ensemble.",
    "Trimestre décevant : Hugo ne fournit pas le travail personnel nécessaire. Il a pourtant les capacités de réussir. Un sursaut est attendu.",
    "Excellent travail en mathématiques. Ses efforts sont constants et sa curiosité est un atout pour la classe. Félicitations !",
    "Rappel : vous avez rendez-vous avec le docteur Martin le mardi 13 octobre 2026 à 9 h 30. En cas d’empêchement, merci de prévenir le cabinet au moins 24 heures à l’avance.",
    "Votre rendez-vous de radiologie est confirmé pour le 21/10/2026 à 14h15. Veuillez arriver dix minutes avant l’heure prévue. Pensez à apporter votre carte Vitale et votre ordonnance.",
    "Centre dentaire des Lilas : votre prochain contrôle aura lieu le lundi 2 novembre à 16 h. Répondez OUI pour confirmer ou NON pour annuler.",
    "Mesdames et messieurs, le TGV numéro 6211 à destination de Marseille Saint-Charles partira voie 7. Il desservira Lyon Part-Dieu et Avignon TGV.",
    "En raison d’un incident technique, le train en provenance de Lille est annoncé avec un retard d’environ 20 minutes. Nous vous prions de nous excuser pour la gêne occasionnée.",
    "Embarquement immédiat pour le vol AF 1234 à destination de Rome, porte K42. Les passagers sont priés de présenter leur carte d’embarquement et une pièce d’identité.",
    "Votre vol pour Montréal est retardé. Nouvelle heure de départ prévue : 18 h 45. Un repas vous sera offert au comptoir de la compagnie.",
    "Préchauffez le four à 180 °C. Dans un saladier, mélangez la farine, le sucre et les œufs, puis ajoutez le beurre fondu. Versez la pâte dans un moule beurré et laissez cuire 35 minutes.",
    "Épluchez les pommes de terre et coupez-les en rondelles fines. Disposez-les dans un plat à gratin, salez, poivrez et couvrez de crème. Enfournez pour une heure environ.",
    "Pour réussir un risotto, ajoutez le bouillon louche par louche en remuant sans cesse. Le riz doit rester légèrement ferme au centre. Terminez avec du parmesan râpé et une noix de beurre.",
    "Écran OLED de 6,7 pouces, fréquence de rafraîchissement de 120 Hz. Batterie de 5 000 mAh compatible avec la charge rapide de 45 W. Connectique : USB-C et Wi-Fi 6.",
    "Téléviseur 4K de 55 pouces, compatible HDR10 et Dolby Vision. Trois ports HDMI 2.1 permettent de brancher une console de jeux à 120 Hz.",
    "Ordinateur portable léger (1,2 kg) équipé de 16 Go de mémoire vive et d’un SSD de 512 Go. Son autonomie atteint douze heures en usage bureautique.",
    "La mer a gardé nos promesses,\nle vent les murmure encore.\nEt quand la nuit tombe sur le port,\nje t’attends jusqu’à l’aurore.",
    "Sous la pluie de novembre, les rues se taisent. Les lampadaires dessinent des cercles d’or sur les pavés mouillés, et la ville respire doucement.",
    "Il était une fois un petit renard qui rêvait de voir la mer. Un matin, il prit son sac à dos et partit sur le chemin, le cœur plein d’espoir.",
    "« Qui a mangé ma soupe ? » demanda le gros ours d’une voix grave. Boucle d’or, cachée sous la table, retenait son souffle.",
    "La petite sorcière avait raté sa potion pour la troisième fois. Au lieu de se transformer en papillon, son chat était devenu tout vert ! Elle éclata de rire.",
    "Les informations publiées sur ce site sont fournies à titre indicatif et ne sauraient engager la responsabilité de l’éditeur. Toute reproduction, même partielle, est interdite sans autorisation préalable.",
    "Conformément au Règlement général sur la protection des données (RGPD), vous disposez d’un droit d’accès, de rectification et de suppression des données vous concernant.",
    "Offre valable jusqu’au 31 décembre 2026, dans la limite des stocks disponibles. Photos non contractuelles.",
    "Enfin les vacances ! ☀️ Direction la Corse avec les copains. #vacances #été",
    "Quel match ce soir ! Bravo aux Bleus pour cette qualification méritée 🇫🇷⚽ #AllezLesBleus",
    "Nouvelle vidéo en ligne : je vous montre comment préparer un vrai tiramisu en dix minutes. 🍰 Le lien est dans ma bio !",
    "Salut ! On se retrouve à 19 h devant le cinéma ? Dis-moi si c’est OK pour toi.",
    "RDV demain à 10 h chez le garagiste. Je te rappelle après pour te dire combien ça coûte.",
    "Pense à acheter du pain, du lait, des œufs, etc. Merci, à ce soir !",
    "Je suis en réunion jusqu’à 15 h, je te réponds dès que possible.",
    "Hier soir, nous avons dîné dans un petit restaurant japonais près de l’Opéra. Les ramen étaient délicieux et les gyozas, croustillants à souhait.",
    "Le chef italien Massimo Bottura a ouvert un nouveau restaurant à Modène. Sa carte met à l’honneur les produits d’Émilie-Romagne.",
    "Lors de son voyage à Séville, Camille a goûté le gazpacho et les churros. Elle a aussi visité l’Alcazar avec son amie Lucía.",
    "Le concert de Billie Eilish à Bercy affichait complet en moins d’une heure. Les fans pourront se consoler avec la retransmission en direct sur YouTube.",
    "La réunion est reportée du lundi 12 au mercredi 14 octobre, de 14 h à 16 h 30. Merci de mettre à jour vos agendas.",
    "Date limite de dépôt des dossiers : 15/01/2027 à minuit. Aucune candidature ne sera acceptée après cette date.",
    "Le musée est ouvert du mardi au dimanche, de 10 h à 18 h. Nocturne le jeudi jusqu’à 21 h 30. Fermeture annuelle le 1er mai.",
    "Né le 3 mars 1998 à Grenoble, Thomas a rejoint l’équipe en septembre 2024.",
    "Pour votre inscription, merci de fournir :\n1. une copie de votre pièce d’identité ;\n2. un justificatif de domicile de moins de trois mois ;\n3. une photo d’identité récente.",
    "Étapes de l’installation :\n1. Téléchargez l’application.\n2. Créez votre compte.\n3. Connectez l’appareil au réseau Wi-Fi.",
    "Au programme de la journée :\n- 9 h : accueil des participants ;\n- 10 h : conférence d’ouverture ;\n- 12 h 30 : déjeuner ;\n- 14 h : ateliers en petits groupes.",
    "Hôtel très bien situé, à deux pas de la plage. La chambre était propre, mais la literie mériterait d’être changée. Le petit-déjeuner est copieux. Je donne 4/5.",
    "Application intuitive et rapide. Depuis la dernière mise à jour, elle plante parfois au démarrage. Note : 3,5/5.",
    "Super expérience avec ce vendeur ! Le produit correspond parfaitement à la description et l’envoi a été rapide. ⭐⭐⭐⭐⭐",
    "Boulangerie artisanale cherche un apprenti pâtissier pour la rentrée. Horaires du matin, deux jours de repos consécutifs. Débutants acceptés.",
    "Association sportive recrute des animateurs titulaires du BAFA pour l’été 2027. Les séjours se déroulent en montagne, du 5 juillet au 25 août.",
    "Maison de caractère en pierre, entièrement rénovée, sur un terrain arboré de 2 000 m². Elle comprend quatre chambres, un bureau et une grande cuisine ouverte sur le séjour.",
    "Colocation : chambre libre dans un T4 lumineux, à dix minutes à pied du campus. Loyer de 450 € par mois, internet compris.",
    "Cyclisme : le Danois a remporté l’étape en solitaire après une échappée de plus de 80 kilomètres. Il conserve le maillot jaune pour la quatrième journée consécutive.",
    "Handball : victoire des Françaises contre la Norvège (29-26) en demi-finale. Elles affronteront le Danemark dimanche pour le titre.",
    "Matinée fraîche avec des gelées par endroits, puis l’après-midi sera ensoleillé. Le vent de nord-est soufflera modérément.",
    "Bon trimestre. Les progrès en anglais sont nets ; il faut maintenant soigner davantage la présentation des copies.",
    "Bonjour, la pharmacie vous informe que votre commande est prête. Elle sera conservée jusqu’au vendredi 9 octobre.",
    "Le métro de la ligne 4 est interrompu entre les stations Châtelet et Montparnasse en raison de travaux. Des bus de remplacement sont mis en place.",
    "Faites revenir l’oignon émincé dans un filet d’huile d’olive. Ajoutez les tomates concassées, une pincée de sel et laissez mijoter à feu doux pendant vingt minutes.",
    "Montre connectée étanche jusqu’à 50 mètres, avec GPS intégré et capteur de fréquence cardiaque. Elle se recharge en une heure grâce à son câble magnétique.",
    "J’ai rangé tes lettres dans une boîte en fer,\net chaque printemps je les relis.\nLes mots ont un peu jauni,\nmais ta voix, elle, n’a pas vieilli.",
    "Ce soir-là, la lune était si ronde que Max crut qu’elle allait tomber dans le jardin. Il ouvrit grand la fenêtre et tendit les bras pour l’attraper.",
    "Les présentes conditions générales de vente s’appliquent à toute commande passée sur le site. Le client reconnaît en avoir pris connaissance avant de valider son achat.",
    "Premier jour dans ma nouvelle boîte et déjà adopté par l’équipe 😄 #nouveaudépart",
    "Désolé pour le retard, j’étais coincé dans les bouchons. J’arrive dans cinq minutes, promis !",
    "Pour le dessert, Akiko a préparé des mochis au thé matcha, et Pedro a apporté le flan de sa grand-mère. Tout le monde s’est régalé.",
    "Nous avons loué une voiture à l’aéroport de Munich pour rejoindre Salzbourg. Le trajet a duré à peine deux heures.",
    "Mise à jour prévue dans la nuit du 7 au 8 octobre, entre 23 h et 2 h. Le service sera temporairement indisponible.",
    "Le colloque se tiendra les 18 et 19 mars 2027 à l’université de Strasbourg.",
    "Ce qu’il faut emporter :\n1. une gourde ;\n2. de la crème solaire ;\n3. un coupe-vent ;\n4. de bonnes chaussures de marche.",
    "Le livre se lit d’une traite. L’intrigue est bien construite, même si la fin m’a un peu laissé sur ma faim. 4/5 pour moi.",
    "Famille recherche un professeur de piano pour des cours à domicile, une heure par semaine, pour un enfant de huit ans. Quartier de la Croix-Rousse.",
    "Les pluies orageuses qui ont touché le Gard ont provoqué des inondations dans plusieurs communes. Les secours sont intervenus à plus de 200 reprises.",
    "Élève agréable en classe, mais trop souvent distrait. Les résultats sont fragiles en physique-chimie. Il faut se reprendre rapidement.",
    "Attention, le quai de départ de votre train a changé. Le TER pour Rouen partira voie B. Nous vous remercions de votre compréhension.",
    "Aspirateur sans fil de 2,5 kg, autonomie jusqu’à 60 minutes. Il est livré avec trois embouts et une station de recharge murale.",
    "Le dragon n’aimait pas cracher du feu. Il préférait de loin cultiver des tomates et lire des histoires aux lapins du village.",
    "Ce message et ses pièces jointes sont confidentiels et destinés exclusivement à leurs destinataires. Si vous l’avez reçu par erreur, merci de le supprimer et d’en avertir l’expéditeur.",
    "Il pleut, il fait froid, et le chauffage est en panne. Vivement le printemps ! 🥶 #lundi",
    "Tu peux m’envoyer le document avant midi ? Je dois le relire avant la réunion. Merci d’avance !",
    "Après trois semaines à New York, Julie est revenue avec une valise pleine de souvenirs et une recette de cheesecake qu’elle compte bien essayer.",
    "Basket : Victor Wembanyama a inscrit 32 points et capté 14 rebonds lors de la victoire des Spurs contre Dallas.",
    "Laissez reposer la pâte à crêpes au moins une heure au réfrigérateur. Faites cuire les crêpes dans une poêle bien chaude, environ une minute de chaque côté.",
    "Local commercial de 85 m² à louer en centre-ville, avec vitrine sur rue piétonne. Idéal pour une boutique ou un salon de coiffure.",
    "Très bon rapport qualité-prix. La machine à café est simple à utiliser et le café est savoureux. Seul bémol : le réservoir est petit. Je lui donne 4,5/5.",
  ],
  en: [
    "Great little café with friendly staff and excellent espresso. The croissants were a bit dry, though. Rating: 4.5/5.",
    "The blender works well, but it's louder than I expected. Shipping was fast and the box arrived intact. 4/5 stars.",
    "Terrible customer service. I waited three weeks for a refund that never came. Rating: 1/5.",
    "We're hiring! Our Denver office is looking for a full-time accountant with at least three years of experience. Salary: $65,000–$75,000 per year, plus benefits. Apply by October 31.",
    "Part-time barista wanted for weekend shifts. No experience is necessary; we'll train you. Please send your résumé to the email address listed below.",
    "Senior Software Engineer (remote). Requirements: strong knowledge of TypeScript, React, and Node.js; experience with AWS is a plus. Competitive salary and flexible hours.",
    "For sale: charming 3 BR/2 BA bungalow on a quiet street. Hardwood floors, updated kitchen, and a fenced backyard. Asking $389,000.",
    "Spacious two-bedroom apartment for rent in downtown Chicago. 1,100 sq ft, in-unit laundry, and a balcony with city views. $2,400/month, utilities not included.",
    "Cozy studio near the university, perfect for a graduate student. Pets are allowed with a deposit. Available November 1.",
    "For sale: a gently used stroller in excellent condition. It folds easily and fits in most car trunks. $80 or best offer.",
    "Lost dog: a small brown terrier named Biscuit, last seen near Maple Park on Sunday evening. Reward offered. Please call if you see him.",
    "The Celtics beat the Knicks 112–104 on Saturday night, extending their winning streak to six games.",
    "Manchester United and Liverpool drew 2–2 at Old Trafford. Both teams scored in the final ten minutes of the match.",
    "She won the final in straight sets, 6–3, 6–4, to claim her first Grand Slam title.",
    "The Kenyan runner crossed the finish line in 2:04:15, setting a new course record.",
    "Expect cloudy skies this morning, with showers developing by midafternoon. Highs will be in the low 60s, and winds will gust up to 25 mph.",
    "A winter storm warning is in effect until 6 a.m. Thursday. Six to ten inches of snow are possible, so avoid unnecessary travel.",
    "Sunny and warm all weekend, with temperatures reaching 85°F on Sunday. Don't forget your sunscreen!",
    "Emma is a conscientious student who consistently completes her assignments on time. She should continue to participate more actively in class discussions.",
    "Jacob has made significant progress in reading this term. However, he needs to focus on checking his work for careless errors in math.",
    "A pleasure to have in class. Liam's creativity and kindness make him a valued member of our group.",
    "Reminder: You have an appointment with Dr. Patel on Tuesday, October 13, at 9:30 a.m. Please arrive 15 minutes early and bring your insurance card.",
    "Your dental cleaning is scheduled for 10/21/2026 at 2:15 PM. Reply YES to confirm or NO to cancel.",
    "This is a reminder that your annual checkup is due. Please call our office to schedule an appointment at your earliest convenience.",
    "Attention, passengers: the 8:15 train to Boston is now boarding on Track 4. Please have your tickets ready.",
    "We regret to inform you that the 17:42 service to Edinburgh has been delayed by approximately 20 minutes due to a signal failure.",
    "Flight BA 287 to San Francisco is now boarding at Gate 22. Passengers in Group 1 may proceed to the gate.",
    "Due to weather conditions, all flights to Toronto have been canceled. Please contact your airline for rebooking options.",
    "Preheat the oven to 350°F. In a large bowl, whisk together the flour, sugar, and baking soda. Fold in the melted butter and bake for 25 to 30 minutes.",
    "Bring a large pot of salted water to a boil. Add the spaghetti and cook until al dente, about nine minutes. Drain, reserving a cup of the pasta water.",
    "Season the chicken generously with salt and pepper. Sear it in a hot skillet for four minutes per side, then let it rest before slicing.",
    "6.1-inch OLED display with a 120 Hz refresh rate. 128 GB of storage, Wi-Fi 6, Bluetooth 5.3, and USB-C fast charging.",
    "This 4K monitor features a 27-inch IPS panel, HDR support, and a built-in USB-C hub that delivers up to 90 W of power.",
    "Lightweight laptop (2.6 lb) with 16 GB of RAM, a 1 TB SSD, and up to 14 hours of battery life.",
    "The river doesn't remember our names,\nbut it carries them anyway.\nAnd when the city lights go dim,\nI'll find you where the willows sway.",
    "Rain on the window, coffee gone cold, and an old song on the radio. Some nights feel endless, and some are over before they begin.",
    "Once upon a time, there was a little owl who was afraid of the dark. Every night, she hid under her wing and waited for the sun to come back.",
    "“Who's been sitting in my chair?” growled Papa Bear. Goldilocks, hiding behind the curtain, held her breath.",
    "The tiny dragon tried to breathe fire, but only bubbles came out. The other dragons laughed, but the children of the village thought it was wonderful.",
    "The information on this website is provided for general informational purposes only and does not constitute legal advice. Use of this site does not create an attorney-client relationship.",
    "All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form without the prior written permission of the publisher.",
    "Offer valid through December 31, 2026, while supplies last. Terms and conditions apply.",
    "Finally finished my first marathon! 🏃‍♀️ My legs are dead, but my heart is full. #RunningCommunity #NeverGiveUp",
    "Just tried the new ramen place on 5th Street. Wow! 🍜 Highly recommend the spicy miso. #foodie",
    "Can't believe it's already October. 🍂 Where did the summer go? #fall",
    "Hey, are we still on for lunch tomorrow? Let me know if noon is OK for you.",
    "I'm running about ten minutes late, sorry! Grab a table and I'll be there ASAP.",
    "Can you pick up a few things on your way home, e.g., milk, eggs, and bread? Thanks!",
    "The meeting has been moved to 3 p.m. today. FYI, the conference room on the second floor is being renovated, so we'll use Room 204 instead.",
    "Last night we had dinner at a tiny Ethiopian restaurant in Washington, D.C. The injera was fantastic, and the owner, Selam, recommended a spicy lentil stew.",
    "Chef Yotam Ottolenghi's new cookbook features dishes inspired by his childhood in Jerusalem.",
    "During our trip to Kyoto, we visited Fushimi Inari and tried matcha ice cream for the first time.",
    "Mariana and Søren met in Copenhagen and now run a small bakery in Lisbon that sells pastéis de nata.",
    "The conference will take place from March 18 to 20, 2027, in Austin, Texas. Early registration closes on January 15.",
    "Deadline for submissions: 2026-11-30 at 11:59 p.m. (UTC). Late entries will not be accepted.",
    "The library is open Monday through Friday, 9 a.m. to 8 p.m., and Saturday from 10 a.m. to 4 p.m. It is closed on Sundays and public holidays.",
    "She was born on 4 July 1990 in Manchester and moved to Sydney in 2015.",
    "To reset your password:\n1. Open the Settings menu.\n2. Select Account.\n3. Tap Reset Password and follow the instructions.",
    "Before the trip, please remember to bring the following:\n1. a valid passport;\n2. a printed copy of your itinerary;\n3. comfortable walking shoes.",
    "Today's agenda:\n- 9:00 a.m. – Welcome and introductions\n- 10:30 a.m. – Workshop on time management\n- 12:00 p.m. – Lunch\n- 1:30 p.m. – Team presentations",
    "The hotel was clean and the front desk team was helpful, but the Wi-Fi kept dropping. Breakfast was decent. Overall, 3.5/5.",
    "Five stars! ⭐⭐⭐⭐⭐ The headphones sound amazing and the noise cancellation is excellent.",
    "The app is easy to use, but it drains my battery quickly. I'd give it 3 out of 5.",
    "A local bakery is seeking an early-morning baker. Applicants must be able to lift 50 lb and work weekends. Starting pay is $18 per hour.",
    "Summer camp counselors needed for July and August 2027. Applicants must be at least 18 years old and certified in first aid.",
    "Beautifully renovated farmhouse on 5 acres with a barn, a pond, and mountain views. 4 BR/3 BA, 2,800 sq ft. Open house on Saturday from 1 to 4 p.m.",
    "Room available in a shared house, a ten-minute walk from campus. $650/month, including utilities and high-speed internet.",
    "The Dodgers clinched the division title with a 5–3 win over the Giants on Tuesday.",
    "In cycling, the Slovenian rider won the mountain stage and retained the yellow jersey for a fifth consecutive day.",
    "A frost advisory is in effect tonight for areas north of the city. Cover sensitive plants and bring pets indoors.",
    "Sophia shows a strong understanding of scientific concepts and asks thoughtful questions. Her lab reports are thorough and well organized.",
    "Your prescription is ready for pickup at the pharmacy. It will be held until Friday, October 9.",
    "Due to track maintenance, there will be no service on the Red Line between Central and Harvard this weekend. Shuttle buses will be provided.",
    "Dice the onion and sauté it in olive oil until translucent. Add the garlic, crushed tomatoes, and a pinch of salt, then simmer for 20 minutes.",
    "Water-resistant smartwatch with built-in GPS, heart rate monitoring, and up to seven days of battery life. Compatible with iOS and Android.",
    "I kept your letters in a tin box\nand read them every spring.\nThe paper's turned a little yellow,\nbut your voice is still the same.",
    "That night, the moon was so round and bright that Max thought it might fall into the garden. He opened his window wide and reached out to catch it.",
    "By using this service, you agree to our Terms of Service and Privacy Policy. We may update these terms at any time without prior notice.",
    "First day at the new job, and the team already feels like family! 😄 #NewBeginnings",
    "Sorry I missed your call; I was in a meeting. I'll call you back in an hour.",
    "For dessert, Akiko made mochi with matcha, and Pedro brought his grandmother's flan. Everyone loved it.",
    "We rented a car at the Munich airport and drove to Salzburg. The trip took less than two hours.",
    "Scheduled maintenance will take place on the night of October 7, from 11 p.m. to 2 a.m. ET. The service may be temporarily unavailable.",
    "The workshop runs every Wednesday at 18:30 from 14/10/2026 to 16/12/2026.",
    "Packing list for the hike:\n1. a water bottle\n2. sunscreen\n3. a windbreaker\n4. sturdy hiking boots",
    "The novel is a real page-turner. The plot is clever, although the ending felt rushed. 4/5 from me.",
    "I'm looking for a piano teacher for my eight-year-old daughter. We would like one lesson per week at our home, preferably on weekday afternoons.",
    "Heavy rain caused flash flooding in several counties overnight. Emergency crews responded to more than 200 calls.",
    "Noah is a friendly and cooperative student, but he is often distracted during lessons. His grades in chemistry need improvement.",
    "Please note that the platform for your train has changed. The 14:05 service to Oxford will now depart from Platform 2.",
    "Cordless vacuum cleaner weighing 5.5 lb, with up to 60 minutes of run time. It comes with three attachments and a wall-mounted charging dock.",
    "The dragon didn't like breathing fire. He much preferred growing tomatoes and reading stories to the rabbits in the village.",
    "This email and any attachments are confidential and intended solely for the addressee. If you have received it in error, please delete it and notify the sender.",
    "Monday, rain, and a broken coffee machine. Send help! ☕😩 #MondayMood",
    "Could you send me the report before noon? I need to review it before the meeting. Thanks in advance!",
    "After three weeks in Buenos Aires, Julia came home with a suitcase full of souvenirs and a recipe for empanadas that she can't wait to try.",
    "Victor Wembanyama scored 32 points and grabbed 14 rebounds as the Spurs defeated Dallas 118–109.",
    "Let the pancake batter rest for at least 30 minutes. Cook the pancakes on a hot griddle until bubbles form on the surface, then flip them.",
    "Retail space for lease in the heart of downtown: 900 sq ft with large street-facing windows. Ideal for a boutique or a café.",
    "Excellent value for money. The coffee maker is simple to use and brews a great cup. My only complaint is the small water tank. 4.5/5.",
  ],
};
for (const lang of ["fr", "en"]) module.exports[lang] = module.exports[lang].map((s) => [s, null, null]);
