// Third blind English corpus (2026-10-02), written before the third round.

module.exports = [
  ["I'll send you the details tommorow.", "tommorow", "tomorrow"],
  ["We was very happy with the result.", "was", "were"],
  ["He don't know what to do.", "don't", "doesn't"],
  ["I am agree with you.", "am agree", "agree"],
  ["Please send me the informations.", "informations", "information"],
  ["She have two brothers.", "have", "has"],
  ["I didn't knew that.", "knew", "know"],
  ["The team are working hard.", null, null],
  ["Let me know if you need anything.", null, null],
  ["I'm hoping to see you soon.", null, null],
  ["It was a great experiance.", "experiance", "experience"],
  ["I look forward to hear from you.", "hear", "hearing"],
  ["They was waiting for us.", "was", "were"],
  ["I have been there last year.", null, null],
  ["The book that I read was amazing.", null, null],
  ["We need to finnish this today.", "finnish", "finish"],
  ["Can you explain me the problem?", null, null],
  ["She speaks english very well.", "english", "English"],
  ["I will meet you on monday.", "monday", "Monday"],
  ["Its not a big deal.", "Its", "It's"],
  ["There are less people here today.", null, null],
  ["I'm going to bed, goodnight!", null, null],
  ["I could of done better.", "could of", "could have"],
  ["Everyone are welcome.", "are", "is"],
  ["The price is to high.", "to", "too"],
  ["We have a meeting at 3pm.", null, null],
  ["I want to loose weight.", "to loose", "to lose"],
  ["The company announced it's results.", "it's", "its"],
  ["I wish you a merry Christmas.", null, null],
  ["He is a honest man.", "a", "an"],
  ["This is an useful tool.", "an", "a"],
  ["I'm affraid I can't come.", "affraid", "afraid"],
  ["We should discuss about this.", "discuss about", "discuss"],
  ["The documents was sent yesterday.", "was", "were"],
  ["My computer is very slow lately.", null, null],
  ["I'm not sure who to ask.", null, null],
  ["Thank you very much for your help.", null, null],
  ["Did she went to the party?", "went", "go"],
  ["It's difficult to say.", null, null],
  ["I have three sister.", "sister", "sisters"],
];
