// Fourth blind English corpus (2026-10-02), written before the fourth round:
// everyday messages, emails and posts.

module.exports = [
  ["I hope this email finds you well.", null, null],
  ["Please find the attached file.", null, null],
  ["Let me know your thoughts.", null, null],
  ["I wanted to follow up on my previous email.", null, null],
  ["Sorry for the late reply.", null, null],
  ["I will be out of the office tommorrow.", "tommorrow", "tomorrow"],
  ["Could you please send me the agenda?", null, null],
  ["We are looking foward to working with you.", "foward", "forward"],
  ["Their is a problem with the server.", "Their", "There"],
  ["The results is very good.", "is", "are"],
  ["He work in a bank.", "work", "works"],
  ["She can sings very well.", "sings", "sing"],
  ["Where is you going?", "is", "are"],
  ["I seen that movie last week.", "seen", "saw"],
  ["Me and my friend went to the cinema.", "Me and my friend", "My friend and I"],
  ["The meeting has been cancelled.", null, null],
  ["Can we reschedule for next week?", null, null],
  ["I'll get back to you as soon as possible.", null, null],
  ["Thanks again for everything!", null, null],
  ["It's been a while since we talked.", null, null],
  ["How was your weekend?", null, null],
  ["That's awesome news, congrats!", null, null],
  ["I'm so tired today lol.", null, null],
  ["Wanna grab lunch tomorrow?", null, null],
  ["We should of booked earlier.", "should of", "should have"],
  ["I recommand this restaurant.", "recommand", "recommend"],
  ["The weather was suprisingly nice.", "suprisingly", "surprisingly"],
  ["I need to buy a new labtop.", "labtop", "laptop"],
  ["This is the begginning of something great.", "begginning", "beginning"],
  ["We had alot of fun.", "alot", "a lot"],
  ["I'm gonna be late, sorry.", null, null],
  ["She don't like spicy food.", "don't", "doesn't"],
  ["There are three peoples in the room.", "peoples", "people"],
  ["I have finish my work.", "finish", "finished"],
  ["He has went home.", "went", "gone"],
  ["Your the best!", "Your", "You're"],
  ["I can't find my keys anywhere.", null, null],
  ["The kids are playing in the garden.", null, null],
  ["We went to Paris last summer.", null, null],
  ["I'm really greatful for your help.", "greatful", "grateful"],
  ["Its raining again.", "Its", "It's"],
  ["Who did you see at the party?", null, null],
  ["The store is closed on sundays.", "sundays", "Sundays"],
  ["Every students must attend.", "students", "student"],
  ["The car needs to be repaired.", null, null],
  ["I've already eaten, thanks.", null, null],
  ["We was supposed to meet at noon.", "was", "were"],
  ["Did you received my message?", "received", "receive"],
  ["I didn't went to school yesterday.", "went", "go"],
];
