// Second blind English corpus (2026-10-02): written before the round that
// focuses on the first suggestion, to measure it honestly.

module.exports = [
  ["I definately want to come.", "definately", "definitely"],
  ["Can you send me the adress?", "adress", "address"],
  ["We should of left earlier.", "should of", "should have"],
  ["He doesnt know the answer.", "doesnt", "doesn't"],
  ["I'm not sure wether it works.", "wether", "whether"],
  ["Thank you for your patience.", null, null],
  ["The goverment announced new rules.", "goverment", "government"],
  ["I need to buy some grocerys.", "grocerys", "groceries"],
  ["She is the most smartest person I know.", "most smartest", "smartest"],
  ["Your going to love this place.", "Your", "You're"],
  ["They're house is near the park.", "They're", "Their"],
  ["I havent seen him today.", "havent", "haven't"],
  ["See you tomorrow!", null, null],
  ["It's a really good idea.", null, null],
  ["The dog wagged it's tail.", "it's", "its"],
  ["I will call you untill noon.", "untill", "until"],
  ["This is a seperate issue.", "seperate", "separate"],
  ["He go to school every day.", "go", "goes"],
  ["I can't wait to see you.", null, null],
  ["We recieved a lot of feedback.", "recieved", "received"],
  ["Please let me know if you have any questions.", null, null],
  ["The begining of the movie was boring.", "begining", "beginning"],
  ["I accidently deleted the file.", "accidently", "accidentally"],
  ["Their going to be late.", "Their", "They're"],
  ["It was a very interresting talk.", "interresting", "interesting"],
  ["She has a lot of experience.", null, null],
  ["I would like a apple.", "a", "an"],
  ["My freind is coming over.", "freind", "friend"],
  ["We are planing a trip to Spain.", "planing", "planning"],
  ["I'm looking forward to hearing from you.", null, null],
  ["The meeting was succesful.", "succesful", "successful"],
  ["He dont like coffee.", "dont", "doesn't"],
  ["I think its going to rain.", "its", "it's"],
  ["Did you finished your homework?", "finished", "finish"],
  ["We have a great team.", null, null],
];
