// Second "dumb mistakes" English corpus (2026-10-06), written after the
// first round of fixes and never used to tune them: the honest measure.

module.exports = [
  ["He's smarter then his brother.", "then", "than"],
  ["I'd rather stay home then go out.", "then", "than"],
  ["We went home and then we slept.", null, null],
  ["I can't except this offer.", "except", "accept"],
  ["Were did you put it?", "Were", "Where"],
  ["Where late again.", "Where", "We're"],
  ["Its getting late.", "Its", "It's"],
  ["Its hot in here.", "Its", "It's"],
  ["The company and its employees.", null, null],
  ["There going home.", "There", "They're"],
  ["There is a problem.", null, null],
  ["Your so right.", "Your", "You're"],
  ["Is that you're phone?", "you're", "your"],
  ["You're going to love it.", null, null],
  ["Whose going first?", "Whose", "Who's"],
  ["Whose bag is this?", null, null],
  ["I need some advise.", "advise", "advice"],
  ["I'd advise you to wait.", null, null],
  ["I'm not sure weather to go.", "weather", "whether"],
  ["The weather is nice.", null, null],
  ["It's to late now.", "to", "too"],
  ["I ate to much.", "to", "too"],
  ["We have to dogs.", "to", "two"],
  ["We have to go.", null, null],
  ["I loose my keys every day.", "loose", "lose"],
  ["Don't brake it.", "brake", "break"],
  ["I could of helped.", "could of", "could have"],
  ["Thanks alot.", "alot", "a lot"],
  ["Me and him are friends.", "Me and him", "He and I"],
  ["Me and you are a team.", "Me and you", "You and I"],
  ["She don't know.", "don't", "doesn't"],
  ["He have finished.", "have", "has"],
  ["I seen him.", "seen", "saw"],
  ["Dont worry.", "Dont", "Don't"],
  ["Can't wait!", null, null],
  ["See you then.", null, null],
];
