// Blind English corpus: written after all tuning, never used to adjust the
// engine. Its score is the honest estimate to quote.

module.exports = [
  ["She dont care about it.", "dont", "doesn't"],
  ["We was late for the meeting.", "was", "were"],
  ["I recieved your email yesterday.", "recieved", "received"],
  ["This is the best restaraunt in town.", "restaraunt", "restaurant"],
  ["Their are many reasons to stay.", "Their", "There"],
  ["He is more taller than me.", "more taller", "taller"],
  ["Could you borrow me your pen?", null, null],
  ["I have went there before.", "went", "gone"],
  ["Its been a long day.", "Its", "It's"],
  ["The meeting is schedualed for Monday.", "schedualed", "scheduled"],
  ["She sings beautifuly.", "beautifuly", "beautifully"],
  ["I am looking forward to meet you.", "meet", "meeting"],
  ["Lets go to the beach.", "Lets", "Let's"],
  ["There house is very big.", "There", "Their"],
  ["I would of called you.", "would of", "would have"],
  ["He has alot of friends.", "alot", "a lot"],
  ["The children is playing outside.", "is", "are"],
  ["I didnt see that coming.", "didnt", "didn't"],
  ["It was an unique opportunity.", "an", "a"],
  ["We need to discus the budget.", "discus", "discuss"],
  ["Thanks for you help.", "you", "your"],
  ["I'm really exited about the trip.", "exited", "excited"],
  ["The weather is nice today.", null, null],
  ["I've been waiting for you for an hour.", null, null],
  ["Let me know when you're ready.", null, null],
  ["She has been working here for three years.", null, null],
  ["Who's coming to the party tonight?", null, null],
  ["We'll see what happens next.", null, null],
  ["Please find attached the document.", null, null],
  ["Have a great weekend!", null, null],
];
