// Second blind French corpus (2026-10-02): written before the round that
// focuses on the first suggestion, to measure it honestly.
// [sentence, wrong text, expected first suggestion]; null = must not be flagged.

module.exports = [
  ["Je sais pas si tu as recu mon message.", "recu", "reçu"],
  ["On se voit demain a la gare.", "a", "à"],
  ["Merci pour ta reponse rapide.", "reponse", "réponse"],
  ["Je t’envoi le fichier ce soir.", "envoi", "envoie"],
  ["Il faut qu’on en parle rapidement.", null, null],
  ["Tu peux me rappeler quand tu peux ?", null, null],
  ["J’ai oublier mes clés chez toi.", "oublier", "oublié"],
  ["Nous avons decidé de partir plus tôt.", "decidé", "décidé"],
  ["Les enfants on bien mangé.", "on", "ont"],
  ["C’est la plus belle journée de ma vie.", null, null],
  ["Je voulais te dire que j’été malade.", "été", "étais"],
  ["Elle est aller au marché.", "aller", "allée"],
  ["Vous pouvez m’envoyer les documents ?", null, null],
  ["Il y a beaucoup de monde aujourd’hui.", null, null],
  ["Je suis désolé pour le retard.", null, null],
  ["Ces vraiment gentil de ta part.", "Ces", "C’est"],
  ["Je n’ai pas encore fini mon travail.", null, null],
  ["Ils ont prit le train de huit heures.", "prit", "pris"],
  ["J’espère que tu vas bien.", null, null],
  ["Je pense que sa va aller.", "sa", "ça"],
  ["La réunion a été reporté à jeudi.", "reporté", "reportée"],
  ["Je t’attend devant le cinéma.", "attend", "attends"],
  ["On a passer une super soirée.", "passer", "passé"],
  ["Je vais essayé de venir.", "essayé", "essayer"],
  ["Tu as vu le dernier film de Nolan ?", null, null],
  ["Il fait vraiment froid ce matin.", null, null],
  ["Je me suis tromper de numéro.", "tromper", "trompé"],
  ["Elle m’a dit quelle viendrait.", "quelle", "qu’elle"],
  ["Je ne c’est pas quoi faire.", "c’est", "sais"],
  ["Nous serons la vers midi.", "la", "là"],
  ["Peux-tu me prêter ton vélo ?", null, null],
  ["Il a acheter une nouvelle voiture.", "acheter", "acheté"],
  ["Je suis trés content de te voir.", "trés", "très"],
  ["Ça fait longtemps qu’on ne s’est pas vus.", null, null],
  ["Je voudrais réserver une table pour deux.", null, null],
  ["Les résultats sont tres bons.", "tres", "très"],
  ["Je vous remercie de votre comprehension.", "comprehension", "compréhension"],
  ["Tu veux venir manger a la maison ?", "a", "à"],
  ["Je suis passer te voir hier.", "passer", "passé"],
  ["Il est arriver en retard.", "arriver", "arrivé"],
  ["Elle a beaucoup travailler cette semaine.", "travailler", "travaillé"],
  ["Je suis allé au travail en vélo.", null, null],
  ["Les filles sont partient en vacances.", "partient", "parties"],
  ["Je te souhaite un bon anniversaire.", null, null],
  ["Nous allons commencé la réunion.", "commencé", "commencer"],
  ["Je n’est pas compris la question.", "est", "ai"],
  ["Tu as raison, je me suis trompé.", null, null],
  ["Il faut que je finisse ce dossier.", null, null],
  ["Ils sont venu nous aider.", "venu", "venus"],
  ["Je cherche un apartement à Paris.", "apartement", "appartement"],
  ["C’est un problème tres important.", "tres", "très"],
  ["On ce voit ce week-end ?", "ce", "se"],
  ["Je vais au magasin acheter du pain.", null, null],
  ["Il me faut encore quelques jours.", null, null],
  ["Je t’ai envoyer un mail.", "envoyer", "envoyé"],
];
