// Fifth blind French corpus (2026-10-06): usage mistakes, anglicisms,
// doubled consonants, accents, irregular verbs, longer agreements.
// Written before the round that targets them.

module.exports = [
  // usage / set phrases
  ["Il pleut, mais on sort comme même.", "comme même", "quand même"],
  ["En faite, je ne viens pas.", "En faite", "En fait"],
  ["Il est parmis nous.", "parmis", "parmi"],
  ["Malgrés la pluie, on est sortis.", "Malgrés", "Malgré"],
  ["Quelques fois, je vais au cinéma.", "Quelques fois", "Quelquefois"],
  ["Quelque soit ton choix, je te soutiens.", "Quelque soit", "Quel que soit"],
  ["Je me rappelle de cette soirée.", "rappelle de", "rappelle"],
  ["Sa se trouve, il a raison.", "Sa", "Ça"],
  ["Voir même plus.", "Voir", "Voire"],
  ["Au jour d’aujourd’hui, tout va vite.", "Au jour d’aujourd’hui", "Aujourd’hui"],
  ["Il a pallié à ce problème.", "pallié à", "pallié"],
  ["Je vais au coiffeur.", "au", "chez le"],
  ["C’est de la faute à Paul.", null, null],
  ["Je suis d’accord avec toi.", null, null],
  ["Tant pis pour lui.", null, null],
  ["Tant pi pour lui.", "Tant pi", "Tant pis"],
  ["Dors bien, à demain.", null, null],
  ["Ci-joint le fichier.", null, null],
  ["Ci-joins le fichier.", "Ci-joins", "Ci-joint"],
  // anglicisms / false friends
  ["Le language de programmation.", "language", "langage"],
  ["Par example, demain.", "example", "exemple"],
  ["Mon addresse a changé.", "addresse", "adresse"],
  ["La connection est lente.", "connection", "connexion"],
  ["Un environement sain.", "environement", "environnement"],
  ["Le dévellopement du projet.", "dévellopement", "développement"],
  ["Je vais t’appeller.", "appeller", "appeler"],
  ["C’est un problème de responsabilitée.", "responsabilitée", "responsabilité"],
  ["Personnelement, je préfère.", "Personnelement", "Personnellement"],
  ["Je suis vraiment désolée, c’est inexcusable.", null, null],
  ["Il est trés intéressant.", "trés", "très"],
  ["Une réponse succinte.", "succinte", "succincte"],
  ["Je suis sûre de moi.", null, null],
  ["Il a réussit son examen.", "réussit", "réussi"],
  ["Elle a finit son travail.", "finit", "fini"],
  ["J’ai dis non.", "dis", "dit"],
  ["Il a mis son manteau.", null, null],
  ["Je l’ai mise sur la table.", null, null],
  // irregular verbs
  ["Ils croivent que c’est vrai.", "croivent", "croient"],
  ["Vous faîtes quoi ce soir ?", "faîtes", "faites"],
  ["Ils voyent bien le problème.", "voyent", "voient"],
  ["Je résous le problème.", null, null],
  ["Il résoud le problème.", "résoud", "résout"],
  ["Nous croyons en toi.", null, null],
  ["Il faut que je fasse mes devoirs.", null, null],
  ["Il faut que je fais mes devoirs.", "fais", "fasse"],
  ["Ils sont venus hier.", null, null],
  ["Je me suis assis.", null, null],
  ["Il s’assoit.", null, null],
  ["Nous sommes allé au parc.", "allé", "allés"],
  ["Elles sont parti tôt.", "parti", "parties"],
  ["Je vous en prie.", null, null],
  ["Vous dîtes vrai.", "dîtes", "dites"],
  ["Ils ont dû partir.", null, null],
  ["Il a du partir.", "du", "dû"],
  ["J’ai du pain.", null, null],
  // agreement in longer sentences
  ["Les fleurs que tu m’as offert sont belles.", "offert", "offertes"],
  ["La lettre que j’ai écrit est partie.", "écrit", "écrite"],
  ["Les livres que j’ai lu étaient passionnants.", "lu", "lus"],
  ["Les problèmes de la société est complexe.", "est", "sont"],
  ["La plupart des gens pense comme ça.", "pense", "pensent"],
  ["Chacun de nous doivent participer.", "doivent", "doit"],
  ["Tout le monde sont là.", "sont", "est"],
  ["C’est moi qui a raison.", "a", "ai"],
  ["C’est toi qui as raison.", null, null],
  ["Ce sont eux qui a gagné.", "a", "ont"],
  ["Une des filles sont venues.", "sont", "est"],
  ["Les enfants dont je t’ai parlé sont là.", null, null],
  ["Les gens qui son venus étaient sympas.", "son", "sont"],
  ["Cette personne sont gentilles.", "sont", "est"],
  ["Mes amis et moi sommes partis.", null, null],
  ["Mes amis et moi sont partis.", "sont", "sommes"],
  // accents and capitals
  ["Je vais a Paris lundi.", "a", "à"],
  ["On se voit Lundi.", "Lundi", "lundi"],
  ["Il parle Français.", "Français", "français"],
  ["Les Français aiment le pain.", null, null],
  ["Il est né en Janvier.", "Janvier", "janvier"],
  ["Ou est la gare ?", "Ou", "Où"],
  ["Ca va bien.", "Ca", "Ça"],
  ["Etes-vous prêt ?", "Etes-vous", "Êtes-vous"],
  ["A demain !", "A", "À"],
  ["Ecole fermée.", "Ecole", "École"],
];
