// Third blind French corpus (2026-10-02), written before the third round.
// [sentence, wrong text, expected first suggestion]; null = must not be flagged.

module.exports = [
  ["Je me suis levé tôt pour aller courir.", null, null],
  ["Il ma dit qu’il viendrait.", "ma", "m’a"],
  ["Tu ma manqué.", "ma", "m’as"],
  ["On a fait la fête toute la nuit.", null, null],
  ["Je suis tellement fatiguer.", "fatiguer", "fatigué"],
  ["Elles se sont rencontrées à Lyon.", null, null],
  ["Quand est-ce que tu reviens ?", null, null],
  ["Je voulait te demander un service.", "voulait", "voulais"],
  ["Nous avons gagner le match.", "gagner", "gagné"],
  ["Je l’ai vu hier au supermarché.", null, null],
  ["Il y avait plein de monde a la fête.", "a", "à"],
  ["Je suis content que tu sois là.", null, null],
  ["Tu as déjà manger ?", "manger", "mangé"],
  ["Je te conseil ce livre.", "conseil", "conseille"],
  ["Elle travail dans une banque.", "travail", "travaille"],
  ["Ils veulent tous venir.", null, null],
  ["Je ne sais pas quoi en penser.", null, null],
  ["Je suis allez voir ma grand-mère.", "allez", "allé"],
  ["Vous avez reçus mon colis ?", "reçus", "reçu"],
  ["Ça me fait plaisir de te voir.", null, null],
  ["Il est partit sans dire au revoir.", "partit", "parti"],
  ["J’ai beaucoup apprécier ton aide.", "apprécier", "apprécié"],
  ["Il fait beau aujourd’hui, on va a la plage.", "a", "à"],
  ["C’est quoi ton numéro ?", null, null],
  ["Je vous est envoyé le contrat.", "est", "ai"],
  ["Je n’ai jamais vu sa.", "sa", "ça"],
  ["Ma soeur habite à Bordeaux.", null, null],
  ["Je vais chercher les enfants à l’école.", null, null],
  ["Je suis vraiment désoler.", "désoler", "désolé"],
  ["On s’est bien amusé hier soir.", null, null],
  ["Ses parents sont très gentils.", null, null],
  ["J’ai rendez-vous chez le médecin.", null, null],
  ["Je pourrai venir demain si tu veux.", null, null],
  ["Il faudrait qu’on se voit bientôt.", "voit", "voie"],
  ["Je sui en retard, désolé.", "sui", "suis"],
  ["Tu crois qu’il va pleuvoir ?", null, null],
  ["Je n’ai pas eu le temps de te répondre.", null, null],
  ["Je t’appelle des que je peux.", "des", "dès"],
  ["Il a oublié son parapluie.", null, null],
  ["Les vacances sont finit.", "finit", "finies"],
  ["Je suis passé à la boulangerie.", null, null],
  ["Merci de m’avoir prévenu.", null, null],
  ["Il pleut depuis ce matin.", null, null],
  ["Vous etes les bienvenus.", "etes", "êtes"],
  ["Je ne peut pas venir ce soir.", "peut", "peux"],
  ["Tu veux que je t’aide ?", null, null],
  ["Je suis arrivé a l’heure.", "a", "à"],
  ["Il a dit qu’il était malade.", null, null],
  ["J’ai acheté du pain et du fromage.", null, null],
  ["Nous nous sommes trompés de route.", null, null],
];
