// Blind French corpus: written after all tuning, never used to adjust the
// engine. Its score is the honest estimate to quote.
// [sentence, wrong text, expected first suggestion]; null = must not be flagged.

module.exports = [
  ["Je les ai vu hier soir.", "vu", "vus"],
  ["Elle s’est acheté une robe.", null, null],
  ["Nous avons manger au restaurant.", "manger", "mangé"],
  ["Il faut que tu fasses attention.", null, null],
  ["Il faut que tu fait attention.", "fait", "fasses"],
  ["Ils sont rentrés tard.", null, null],
  ["Je suis partis tôt ce matin.", "partis", "parti"],
  ["Les chats dort sur le canapé.", "dort", "dorment"],
  ["C’est une belle maison blanc.", "blanc", "blanche"],
  ["J’ai trouvé ses clés sur la table.", null, null],
  ["Ce sont mes amie.", "amie", "amies"],
  ["Je vais au cinema ce soir.", "cinema", "cinéma"],
  ["Il a reussi son examen.", "reussi", "réussi"],
  ["C’est vraiment dommage.", null, null],
  ["Je te rapelle demain.", "rapelle", "rappelle"],
  ["Nous nous sommes rencontré à Paris.", "rencontré", "rencontrés"],
  ["Il y a beaucoup de choses a faire.", "a", "à"],
  ["Tu as raison, sa ne sert à rien.", "sa", "ça"],
  ["Je ne sais pas si il viendra.", "si il", "s’il"],
  ["Elle est arrivée en avance.", null, null],
  ["Ont doit partir maintenant.", "Ont", "On"],
  ["Je voulais te dire merci.", null, null],
  ["Elles ont été invité à la fête.", "invité", "invitées"],
  ["Peux-tu m’envoyer le fichier ?", null, null],
  ["Il pleuvait quand je suis sortit.", "sortit", "sorti"],
  ["J’ai acheter du pain.", "acheter", "acheté"],
  ["Le travail est presque finit.", "finit", "fini"],
  ["Je n’ai jamais vu sa.", "sa", "ça"],
  ["Ils on raison.", "on", "ont"],
  ["Il est tellement gentil.", null, null],
  ["Je suis desolé pour hier.", "desolé", "désolé"],
  ["Les résultats sont encourageant.", "encourageant", "encourageants"],
  ["Elle a prit sa décision.", "prit", "pris"],
  ["Je te souhaite une bonne journée.", null, null],
  ["Il a oublié de m’appeler.", null, null],
  ["Ces enfants sont adorable.", "adorable", "adorables"],
  ["On s’est bien amusés.", null, null],
  ["Tu peut compter sur moi.", "peut", "peux"],
  ["Je l’ai deja fait.", "deja", "déjà"],
  ["Ça fait plaisir de te voir.", null, null],
];
