// Fourth blind French corpus (2026-10-02), written before the fourth round:
// everyday messages, emails and posts.
// [sentence, wrong text, expected first suggestion]; null = must not be flagged.

module.exports = [
  ["Bonsoir, je me permet de vous relancer.", "permet", "permets"],
  ["Je vous joint le document en pièce jointe.", "joint", "joins"],
  ["N’hésitez pas a me contacter.", "a", "à"],
  ["Je reste à votre disposition pour tout renseignement.", null, null],
  ["Merci d’avance pour votre retour.", null, null],
  ["Je vous pris d’agréer mes salutations distinguées.", "pris", "prie"],
  ["Cordialement, Julien.", null, null],
  ["Suite à notre conversation, je vous envois le devis.", "envois", "envoie"],
  ["Pouvez vous me confirmer la date ?", "Pouvez vous", "Pouvez-vous"],
  ["Je suis disponible mardi ou mercredi.", null, null],
  ["La livraison est prévu pour vendredi.", "prévu", "prévue"],
  ["Les factures ont été envoyé hier.", "envoyé", "envoyées"],
  ["Nous avons bien reçu votre commande.", null, null],
  ["Je n’ai toujours pas reçu de réponse.", null, null],
  ["Il faudrait que vous me rappelez.", "rappelez", "rappeliez"],
  ["J’ai hâte de vous rencontrer.", null, null],
  ["Ils se sont bien amusés.", null, null],
  ["Elle s’est fait mal au genou.", null, null],
  ["Ça c’est passé très vite.", "c’est", "s’est"],
  ["Je savais pas que tu venais.", null, null],
  ["T’inquiète, je gère.", null, null],
  ["Je suis en train de manger.", null, null],
  ["Je suis entrain de travailler.", "entrain", "en train"],
  ["Je vais me coucher, bonne nuit !", null, null],
  ["Grave, c’était trop bien !", null, null],
  ["Tu fais quoi ce soir ?", null, null],
  ["On se capte plus tard.", null, null],
  ["J’ai pas eu le temps de le faire.", null, null],
  ["Il a eu sont permis du premier coup.", "sont", "son"],
  ["Ils ont fait leurs devoirs.", null, null],
  ["Ces enfants sont adorables.", null, null],
  ["Je l’ai déjà fait plusieurs fois.", null, null],
  ["Qu’est-ce que tu en penses ?", null, null],
  ["Je ne comprend pas ce qu’il veut.", "comprend", "comprends"],
  ["Tu as finis ton travail ?", "finis", "fini"],
  ["Elle a pris ces affaires et elle est partie.", null, null],
  ["Quelque soit le résultat, on sera fiers.", "Quelque soit", "Quel que soit"],
  ["Je préfère qu’on se voit demain.", "voit", "voie"],
  ["Il y a quelques années, j’habitais à Lille.", null, null],
  ["Ce film est vraiment génial, je te le conseille.", null, null],
  ["Je ne sais pas si je pourrais venir.", null, null],
  ["J’aurais aimé être là.", null, null],
  ["Je serais ravi de vous aider.", null, null],
  ["Il m’a demandé si j’étais libre.", null, null],
  ["Je me suis acheté un nouveau téléphone.", null, null],
  ["Les photos que j’ai pris sont floues.", "pris", "prises"],
  ["La voiture que j’ai acheté est rouge.", "acheté", "achetée"],
  ["Je te l’avais dit !", null, null],
  ["Il est venu me voir hier soir.", null, null],
  ["Je suis tomber dans les escaliers.", "tomber", "tombé"],
  ["Ils ont décider de partir.", "décider", "décidé"],
  ["Nous allons vous envoyez le colis.", "envoyez", "envoyer"],
  ["Je doit partir maintenant.", "doit", "dois"],
  ["Tu doit faire attention.", "doit", "dois"],
  ["Les gens pense que c’est facile.", "pense", "pensent"],
  ["Mes parents habite à Nantes.", "habite", "habitent"],
  ["Il y a beaucoup de choses a faire.", "a", "à"],
  ["J’ai plein de trucs à te raconter.", null, null],
  ["Je n’en peux plus de ce boulot.", null, null],
  ["Ça fait plaisir, merci beaucoup !", null, null],
  ["Bonne journée à toi aussi.", null, null],
  ["Je t’envoie ça demain matin.", null, null],
  ["C’est pas grave, ça arrive.", null, null],
  ["On se retrouve devant la gare à 18h.", null, null],
  ["Pense à acheter du lait.", null, null],
  ["Je crois que j’ai perdu mes clés.", null, null],
  ["Il fait super chaud aujourd’hui.", null, null],
  ["Vous avez passé de bonnes vacances ?", null, null],
];
