// French regression corpus: common mistakes and the correction we expect.
// Each case: [sentence, wrong text, expected first suggestion]
// An expected value of null means "this must NOT be flagged".

module.exports = [
  // ---- Homophones grammaticaux
  ["Il a mangé à la maison.", null, null],
  ["Il à mangé une pomme.", "à", "a"],
  ["Je vais a Paris demain.", "a", "à"],
  ["Elle est contente et elle rit.", null, null],
  ["Il et parti hier soir.", "et", "est"],
  ["Mon frère est grand est fort.", "est", "et"],
  ["Tu veux du thé ou du café ?", null, null],
  ["Je ne sais pas ou il habite.", "ou", "où"],
  ["Ils son partis en vacances.", "son", "sont"],
  ["Il a perdu sont chien.", "sont", "son"],
  ["Ils on mangé ensemble.", "on", "ont"],
  ["Ont va au cinéma ce soir.", "Ont", "On"],
  ["Il se lave les mains. Ce livre est à moi.", null, null],
  ["Il ce lave les mains.", "ce", "se"],
  ["Se livre est très intéressant.", "Se", "Ce"],
  ["Je lui ai donné leurs livres.", null, null],
  ["Je leurs ai dit de venir.", "leurs", "leur"],
  ["Pose le livre la, sur la table.", "la", "là"],
  ["Sa ne va pas du tout.", "Sa", "Ça"],
  ["Il peu venir demain.", "peu", "peut"],
  ["Il mange un peut de pain.", "peut", "peu"],
  ["Quand à moi, je reste ici.", "Quand", "Quant"],
  ["Il ma dit de venir.", "ma", "m’a"],
  ["Il ta appelé ce matin.", "ta", "t’a"],
  ["Elle sait trompée de chemin.", "sait", "s’est"],
  ["Je ne sais pas quel heure il est.", "quel", "quelle"],
  ["Je pense quelle viendra demain.", "quelle", "qu’elle"],
  ["Il faut que tu soit à l’heure.", "soit", "sois"],
  ["Si tu veux, sa marche.", "sa", "ça"],
  ["Il y a plusieurs possibilité.", "possibilité", "possibilités"],

  // ---- é / er / ez / ait / ai
  ["Je vais mangé une pomme.", "mangé", "manger"],
  ["Il faut travaillé plus.", "travaillé", "travailler"],
  ["J’ai manger une pomme.", "manger", "mangé"],
  ["Il a décider de partir.", "décider", "décidé"],
  ["Elle veut acheté une voiture.", "acheté", "acheter"],
  ["Vous devez travailler plus.", null, null],
  ["Vous parler trop vite.", "parler", "parlez"],
  ["Je viens te parlé.", "parlé", "parler"],
  ["Je vais te le donné demain.", "donné", "donner"],
  ["Il est aller au marché.", "aller", "allé"],
  ["Je suis passer te voir.", "passer", "passé"],
  ["Pour réussir, il faut étudié.", "étudié", "étudier"],
  ["Il commence à travaillé.", "travaillé", "travailler"],
  ["Elle a finit son travail.", "finit", "fini"],
  ["Il a prit le train.", "prit", "pris"],
  ["J’ai mis la table.", null, null],

  // ---- Accords
  ["Les enfant jouent dehors.", "enfant", "enfants"],
  ["J’ai acheté des pomme.", "pomme", "pommes"],
  ["Elle est parti tôt.", "parti", "partie"],
  ["Elles sont arrivé hier.", "arrivé", "arrivées"],
  ["Les maisons sont grande.", "grande", "grandes"],
  ["Une belle journée ensoleillé.", "ensoleillé", "ensoleillée"],
  ["Les pommes que j’ai mangé étaient bonnes.", "mangé", "mangées"],
  ["Ces problème sont résolus.", "problème", "problèmes"],
  ["Tous les jour, je cours.", "jour", "jours"],
  ["Toute les personnes sont là.", "Toute", "Toutes"],
  ["Ils sont tout contents.", null, null],
  ["Mes amis sont venu me voir.", "venu", "venus"],
  ["La plupart des gens pense que c’est vrai.", "pense", "pensent"],

  // ---- Conjugaison
  ["Je doit partir maintenant.", "doit", "dois"],
  ["Tu peut venir avec moi.", "peut", "peux"],
  ["Ils mange au restaurant.", "mange", "mangent"],
  ["Nous allont au cinéma.", "allont", "allons"],
  ["Je veut un café.", "veut", "veux"],
  ["Tu va bien ?", "va", "vas"],
  ["Il faut que tu viens demain.", "viens", "viennes"],
  ["Si j’aurais su, je serais venu.", "aurais", "avais"],
  ["Ils croient que tu es malade.", null, null],
  ["Vous faite trop de bruit.", "faite", "faites"],
  ["Vous dites la vérité.", null, null],
  ["Je suis sur que tu as raison.", "sur", "sûr"],
  ["J’ai vu ton message hier.", null, null],
  ["Ils ont prient pour la paix.", "prient", "prié"],

  // ---- Fautes d’orthographe fréquentes
  ["Merci beaucoups pour ton aide.", "beaucoups", "beaucoup"],
  ["Il est venu malgrés la pluie.", "malgrés", "malgré"],
  ["Il fait beau aujourd’hui.", null, null],
  ["Il fait beau aujourdhui.", "aujourdhui", "aujourd’hui"],
  ["Il est parmis nous.", "parmis", "parmi"],
  ["Je dois développer ce projet.", null, null],
  ["Je dois dévelloper ce projet.", "dévelloper", "développer"],
  ["Je vais l’appeller demain.", "appeller", "appeler"],
  ["La connection internet est lente.", "connection", "connexion"],
  ["C’est un language de programmation.", "language", "langage"],
  ["Il y a eu un accident hier.", null, null],
  ["Il a eu un accident hier soir avec sa voitture.", "voitture", "voiture"],
  ["C’est vraiment génial.", null, null],
  ["C’est vraimant génial.", "vraimant", "vraiment"],
  ["Je suis désolé pour le rettard.", "rettard", "retard"],
  ["Il fait un temps magnifique.", null, null],
  ["Il fait un temp magnifique.", "temp", "temps"],
  ["C’est un problême important.", "problême", "problème"],
  ["Je n’ai pas le temps maintenent.", "maintenent", "maintenant"],
  ["Je suis content de te voire.", "voire", "voir"],
  ["Il faut que je règle ça rapidement.", null, null],
  ["Il a acceuilli ses invités.", "acceuilli", "accueilli"],
  ["C’est une bonne occassion.", "occassion", "occasion"],
  ["Je te remercie d’avance.", null, null],
  ["Il est arrivé en retard comme dabitude.", "dabitude", "d’habitude"],
  ["Je suis vraiment fatiguer ce soir.", "fatiguer", "fatigué"],

  // ---- Accents oubliés (frappe rapide)
  ["Il est tres gentil.", "tres", "très"],
  ["Je l’ai deja vu.", "deja", "déjà"],
  ["Il va a l’ecole.", "ecole", "école"],
  ["C’est la meme chose.", "meme", "même"],
  ["On se voit apres le repas.", "apres", "après"],
  ["Ce n’est pas un probleme.", "probleme", "problème"],
  ["Il faut etre patient.", "etre", "être"],
  ["Il est arrive hier.", "arrive", "arrivé"],
  ["Je suis alle au parc.", "alle", "allé"],
  ["La reunion commence a midi.", "reunion", "réunion"],
  ["C’etait vraiment bien.", "etait", "était"],
  ["Il faut que tu reflechisses.", "reflechisses", "réfléchisses"],
  ["Voila ce que je voulais dire.", "Voila", "Voilà"],
  ["Ou est la gare ?", "Ou", "Où"],
  ["Il a ete malade.", "ete", "été"],

  // ---- Apostrophes oubliées
  ["Jai faim.", "Jai", "J’ai"],
  ["Cest vraiment bien.", "Cest", "C’est"],
  ["Jaime beaucoup ce film.", "Jaime", "J’aime"],
  ["Il va a lecole.", "lecole", "l’école"],
  ["Je ne sais pas sil viendra.", "sil", "s’il"],
  ["Il ny a personne.", "ny", "n’y"],
  ["Je nai pas compris.", "nai", "n’ai"],
  ["Quest-ce que tu fais ?", "Quest-ce", "Qu’est-ce"],

  // ---- Typographie et ponctuation
  ["Bonjour , comment vas-tu ?", " ,", ","],
  ["Il est venu,il est reparti.", "il", " il"],
  ["Il est venu.Il est reparti.", "Il", " Il"],
  ["C’est le le meilleur.", "le le", "le"],
  ["Je viens viens demain.", "viens viens", "viens"],

  // ---- Phrases correctes : rien ne doit être signalé
  ["Le chat dort sur le canapé.", null, null],
  ["Nous sommes allés à la plage hier.", null, null],
  ["Elle s’est levée tôt ce matin.", null, null],
  ["Les enfants ont joué toute la journée.", null, null],
  ["Je pense qu’il viendra demain soir.", null, null],
  ["Est-ce que tu peux m’aider ?", null, null],
  ["Il faut que nous partions maintenant.", null, null],
  ["Les fleurs que j’ai cueillies sont belles.", null, null],
  ["Quoi qu’il arrive, je serai là.", null, null],
  ["Merci pour ton message, à bientôt !", null, null],
  // Reported by a user (2026-10-06).
  ["C'ait deux la bombe.", "C'ait", "C'est"],
  ["C'est de la bombe, c'ait génial.", "c'ait", "c'est"],
  ["Il s'ait trompé de route.", "s'ait", "s'est"],
  ["C'est deux la bombe.", "deux", "de"],
  ["Qu'il ait raison ou pas, on verra.", null, null],
  ["Nous étions deux la semaine dernière.", null, null],
  ["Il en a pris deux la semaine dernière.", null, null],
  ["C'est deux las bombe.", "deux", "de"],
  ["C'est las bombe.", "las", "la"],
  ["Il prend las voiture.", "las", "la"],
  ["Je suis las de tout ça.", null, null],
  ["Un homme las marche lentement.", null, null],
  // Typos that make another real word (2026-10-06).
  ["Elle et partie.", "et", "est"],
  ["C'est du la bombe.", "du", "de"],
  ["Je suis ne en 1990.", "ne", "né"],
  ["Il fait chaux.", "chaux", "chaud"],
  ["Je te le dirai demain, ces promis.", "ces", "c’est"],
  ["Tu viens avec mois ?", "mois", "moi"],
  ["Je t'aime de tout mont cœur.", "mont", "mon"],
  ["Il parle trop for.", "for", "fort"],
  ["Il fait beau aujourd hui.", "aujourd hui", "aujourd’hui"],
  ["Il mange dans le maisons.", "le", "les"],
  ["Elle et moi, on part.", null, null],
  ["Ça fait trois mois.", null, null],
  ["Le mont Blanc est haut.", null, null],
  ["En mon for intérieur, je sais.", null, null],
];
