// Second "dumb mistakes" French corpus (2026-10-06), written after the
// first round of fixes and never used to tune them: the honest measure.

module.exports = [
  ["Sa marche pas.", "Sa", "Ça"],
  ["Sa dépend de toi.", "Sa", "Ça"],
  ["Elle a oublié ça veste.", "ça", "sa"],
  ["Ses pas possible.", "Ses", "C’est"],
  ["Cest pas grave.", "Cest", "C’est"],
  ["Il cest trompé.", "cest", "s’est"],
  ["On ces vu hier.", "ces", "s’est"],
  ["Je cest pas.", "cest", "sais"],
  ["Ils son arrivés hier.", "son", "sont"],
  ["Elle a perdu sont sac.", "sont", "son"],
  ["Mes parents on une maison.", "on", "ont"],
  ["Ont se voit demain ?", "Ont", "On"],
  ["Il et malade.", "et", "est"],
  ["Tu habite ou ?", "habite", "habites"],
  ["Je sais pas ou aller.", "ou", "où"],
  ["Il y a du monde la-bas.", "la-bas", "là-bas"],
  ["Il ma appelé hier.", "ma", "m’a"],
  ["Il ta dit quoi ?", "ta", "t’a"],
  ["Elle la acheté hier.", "la", "l’a"],
  ["Il ce prépare.", "ce", "se"],
  ["Ce soir on sort.", null, null],
  ["Il se fait tard.", null, null],
  ["Je peu pas.", "peu", "peux"],
  ["Il peux venir.", "peux", "peut"],
  ["Tu veut un café ?", "veut", "veux"],
  ["Quand à moi, je reste.", "Quand", "Quant"],
  ["Je sais quand il vient.", null, null],
  ["Je ne lui est rien dit.", "est", "ai"],
  ["J’ai tous compris.", "tous", "tout"],
  ["Tout les jours.", "Tout", "Tous"],
  ["On a manger ensemble.", "manger", "mangé"],
  ["Je vais te montrer.", null, null],
  ["Je vais te montré.", "montré", "montrer"],
  ["Vous pouvez m’appelez.", "appelez", "appeler"],
  ["Il a était malade.", "était", "été"],
  ["J’ai étais surpris.", "étais", "été"],
  ["Si j’aurais su, je serais venu.", "aurais", "avais"],
  ["Si tu viens, je serais content.", "serais", "serai"],
  ["Je fesait la vaisselle.", "fesait", "faisais"],
  ["Ils disent toujours ça.", null, null],
  ["Vous faites quoi ?", null, null],
  ["Chui fatigué.", "Chui", "Je suis"],
  ["Kesk tu fais ?", "Kesk", "Qu’est-ce que"],
  ["Jvais dormir.", "Jvais", "Je vais"],
  ["Ya un problème.", "Ya", "Il y a"],
  ["Tinquiète pas.", "Tinquiète", "T’inquiète"],
  ["G pas le temps.", "G", "J’ai"],
  ["Jsais pas.", "Jsais", "Je sais"],
  ["C trop bien.", "C", "C’est"],
  ["Ta fini ?", "Ta", "T’as"],
  ["Dacc, à demain.", "Dacc", "D’accord"],
  ["Je suis trop contente.", null, null],
  ["Merci beaucoup pour tout.", null, null],
];
