// The missing "ne" of a negation (2026-10-07), and look-alikes that are correct.
// [sentence, wrong text, expected first suggestion]; null = must not be flagged.

module.exports = [
  ["Quel dommage de pas l’avoir produite comme la Clio V6 !", "pas", "ne pas"],
  ["Je t’ai dit de pas y aller.", "pas", "ne pas"],
  ["Il promet de jamais recommencer.", "jamais", "ne jamais"],
  ["Fais attention pour pas tomber.", "pas", "ne pas"],
  ["Ouais, je sais pas trop, on verra demain.", "sais", "ne sais"],
  ["C’est pas grave, ça arrive à tout le monde.", "C’", "Ce n’"],
  ["J'ai pas eu le temps de finir, désolée.", "ai", "n’ai"],
  ["Je trouve pas mes clés, tu les as vues ?", "trouve", "ne trouve"],
  ["Je veux pas te déranger, mais tu aurais deux minutes ?", "veux", "ne veux"],
  ["On sait jamais, prends un parapluie.", "sait", "ne sait"],
  ["Je comprends pas pourquoi il a dit ça.", "comprends", "ne comprends"],
  ["Il vient pas ce soir, il est malade.", "vient", "ne vient"],
  ["Laisse tomber, c’est pas important.", "c’", "ce n’"],
  ["Je peux pas ce soir, on remet ça à demain ?", "peux", "ne peux"],
  ["Tu vas pas le croire, j'ai gagné au loto !", "vas", "ne vas"],
  ["Ça marche pas chez moi.", "marche", "ne marche"],
  ["Je préfère ne pas y aller.", null, null],
  ["Je te demande de ne pas le faire.", null, null],
  ["Il avance pas à pas.", null, null],
  ["Il y a pas mal de monde ce soir.", null, null],
  ["C’est le meilleur film que j’ai jamais vu.", null, null],
  ["On a trouvé un hôtel pour pas cher.", null, null],
  ["Il a fait deux pas de plus.", null, null],
  ["Pourquoi pas ?", null, null],
  ["Il ne fait pas un pas sans elle.", null, null],
  ["Je n’ai jamais dit ça.", null, null],
  ["Plus que jamais, il faut y croire.", null, null],
  ["Il marche à pas de loup.", null, null],
  ["Le pas de la porte est mouillé.", null, null],
  ["Tu viens ou pas ?", null, null],
];
